// Code generated by the Lingua Franca compiler from:
// file://home/foobar/EECS149Proj/PololuCharacterization/src/ProjWifi.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/EECS149Proj/PololuCharacterization/src-gen/ProjWifi"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
#include "_display.h"
#include "_projwifi_main.h"
typedef enum {
    projwifi_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[projwifi_main],projwifi_main,_lf_number_of_workers,0,2,0,0,3,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _projwifi_main_main_self_t* projwifi_main_self[1];
    SUPPRESS_UNUSED_WARNING(projwifi_main_self);
    _display_self_t* projwifi_disp_self[1];
    SUPPRESS_UNUSED_WARNING(projwifi_disp_self);
    // ***** Start initializing ProjWifi of class ProjWifi
    projwifi_main_self[0] = new__projwifi_main();
    projwifi_main_self[0]->base.environment = &envs[projwifi_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    envs[projwifi_main].startup_reactions[startup_reaction_count[projwifi_main]++] = &projwifi_main_self[0]->_lf__reaction_0;
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    // Initializing action ProjWifi.blue
    projwifi_main_self[0]->_lf__blue.offset = 0;
    projwifi_main_self[0]->_lf__blue.period = -1;
    projwifi_main_self[0]->_lf__blue.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(projwifi_main_self[0]->_lf__blue),
    0);
    projwifi_main_self[0]->_lf__blue.status = absent;
    projwifi_main_self[0]->_lf__reaction_0.deadline = NEVER;
    projwifi_main_self[0]->_lf__reaction_1.deadline = NEVER;
    {
        // ***** Start initializing ProjWifi.disp of class Display
        projwifi_disp_self[0] = new__display();
        projwifi_disp_self[0]->base.environment = &envs[projwifi_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        projwifi_disp_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        projwifi_disp_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        projwifi_disp_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        projwifi_disp_self[0]->_lf_line3_width = -2;
        envs[projwifi_main].startup_reactions[startup_reaction_count[projwifi_main]++] = &projwifi_disp_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        projwifi_disp_self[0]->_lf__reaction_0.deadline = NEVER;
        projwifi_disp_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing ProjWifi.disp
    }
    //***** End initializing ProjWifi
    // **** Start deferred initialize for ProjWifi
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of ProjWifi.
        projwifi_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of ProjWifi
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of ProjWifi.
        projwifi_main_self[0]->_lf__reaction_1.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        projwifi_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &projwifi_main_self[0]->base.allocations);
        projwifi_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &projwifi_main_self[0]->base.allocations);
        projwifi_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &projwifi_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                projwifi_main_self[0]->_lf__reaction_1.output_produced[count++] = &projwifi_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                projwifi_main_self[0]->_lf__reaction_1.output_produced[count++] = &projwifi_main_self[0]->_lf_disp.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of ProjWifi
    
        // **** Start deferred initialize for ProjWifi.disp
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of ProjWifi.disp.
            projwifi_disp_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of ProjWifi.disp
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of ProjWifi.disp.
            projwifi_disp_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of ProjWifi.disp
        
        }
        // **** End of deferred initialize for ProjWifi.disp
    }
    // **** End of deferred initialize for ProjWifi
    // **** Start non-nested deferred initialize for ProjWifi
    // Set number of destination reactors for port disp.line0.
    // Iterate over range ProjWifi.disp.line0(0,1)->[ProjWifi.disp.line0(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        projwifi_main_self[src_runtime]->_lf_disp.line0._base.num_destinations = 1;
        projwifi_main_self[src_runtime]->_lf_disp.line0._base.source_reactor = (self_base_t*)projwifi_main_self[src_runtime];
    }
    // Set number of destination reactors for port disp.line1.
    // Iterate over range ProjWifi.disp.line1(0,1)->[ProjWifi.disp.line1(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        projwifi_main_self[src_runtime]->_lf_disp.line1._base.num_destinations = 1;
        projwifi_main_self[src_runtime]->_lf_disp.line1._base.source_reactor = (self_base_t*)projwifi_main_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ProjWifi.disp.line0(0,1)->[ProjWifi.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of ProjWifi triggers 1 downstream reactions
            // through port ProjWifi.disp.line0.
            projwifi_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of ProjWifi, allocate an
            // array of trigger pointers for downstream reactions through port ProjWifi.disp.line0
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &projwifi_main_self[src_runtime]->base.allocations); 
            projwifi_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ProjWifi.disp.line1(0,1)->[ProjWifi.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of ProjWifi triggers 1 downstream reactions
            // through port ProjWifi.disp.line1.
            projwifi_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of ProjWifi, allocate an
            // array of trigger pointers for downstream reactions through port ProjWifi.disp.line1
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &projwifi_main_self[src_runtime]->base.allocations); 
            projwifi_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ProjWifi.disp.line0(0,1)->[ProjWifi.disp.line0(0,1)] and ProjWifi.disp.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ProjWifi.disp.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ProjWifi.disp.line0's trigger struct.
                projwifi_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &projwifi_disp_self[dst_runtime]->_lf__line0;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges ProjWifi.disp.line1(0,1)->[ProjWifi.disp.line1(0,1)] and ProjWifi.disp.line1(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ProjWifi.disp.line1(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ProjWifi.disp.line1's trigger struct.
                projwifi_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &projwifi_disp_self[dst_runtime]->_lf__line1;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for ProjWifi.disp
    
    
    
    
    // **** End of non-nested deferred initialize for ProjWifi.disp
    // **** End of non-nested deferred initialize for ProjWifi
    // Connect inputs and outputs for reactor ProjWifi.
    // Connect inputs and outputs for reactor ProjWifi.disp.
    // Connect ProjWifi.disp.line0(0,1)->[ProjWifi.disp.line0(0,1)] to port ProjWifi.disp.line0(0,1)
    // Iterate over ranges ProjWifi.disp.line0(0,1)->[ProjWifi.disp.line0(0,1)] and ProjWifi.disp.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ProjWifi.disp.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            projwifi_disp_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&projwifi_main_self[src_runtime]->_lf_disp.line0;
        }
    }
    // Connect ProjWifi.disp.line1(0,1)->[ProjWifi.disp.line1(0,1)] to port ProjWifi.disp.line1(0,1)
    // Iterate over ranges ProjWifi.disp.line1(0,1)->[ProjWifi.disp.line1(0,1)] and ProjWifi.disp.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ProjWifi.disp.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            projwifi_disp_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&projwifi_main_self[src_runtime]->_lf_disp.line1;
        }
    }
    {
    }
    // Add port ProjWifi.disp.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[projwifi_main].is_present_fields[0 + count] = &projwifi_main_self[0]->_lf_disp.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[projwifi_main]._lf_intended_tag_fields[0 + count] = &projwifi_main_self[0]->_lf_disp.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port ProjWifi.disp.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[projwifi_main].is_present_fields[1 + count] = &projwifi_main_self[0]->_lf_disp.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[projwifi_main]._lf_intended_tag_fields[1 + count] = &projwifi_main_self[0]->_lf_disp.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action ProjWifi.blue to array of is_present fields.
        envs[projwifi_main].is_present_fields[2] 
                = &projwifi_main_self[0]->_lf_blue.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action ProjWifi.blue to array of intended_tag fields.
        envs[projwifi_main]._lf_intended_tag_fields[2] 
                = &projwifi_main_self[0]->_lf_blue.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    
    // Set reaction priorities for ReactorInstance ProjWifi
    {
        projwifi_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        projwifi_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        projwifi_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        projwifi_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
    
        // Set reaction priorities for ReactorInstance ProjWifi.disp
        {
            projwifi_disp_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            projwifi_disp_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            projwifi_disp_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            projwifi_disp_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
