// Code generated by the Lingua Franca compiler from:
// file://home/foobar/EECS149Proj/PololuCharacterization/src/BumpDisplay.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/EECS149Proj/PololuCharacterization/src-gen/BumpDisplay"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_bump.h"
#include "_display.h"
#include "_bumpdisplay_main.h"
typedef enum {
    bumpdisplay_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[bumpdisplay_main],bumpdisplay_main,_lf_number_of_workers,1,2,0,0,5,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _bumpdisplay_main_main_self_t* bumpdisplay_main_self[1];
    SUPPRESS_UNUSED_WARNING(bumpdisplay_main_self);
    _bump_self_t* bumpdisplay_bump_self[1];
    SUPPRESS_UNUSED_WARNING(bumpdisplay_bump_self);
    _display_self_t* bumpdisplay_disp_self[1];
    SUPPRESS_UNUSED_WARNING(bumpdisplay_disp_self);
    // ***** Start initializing BumpDisplay of class BumpDisplay
    bumpdisplay_main_self[0] = new__bumpdisplay_main();
    bumpdisplay_main_self[0]->base.environment = &envs[bumpdisplay_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    // Initializing action BumpDisplay.clear
    bumpdisplay_main_self[0]->_lf__clear.offset = 0;
    bumpdisplay_main_self[0]->_lf__clear.period = -1;
    bumpdisplay_main_self[0]->_lf__clear.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(bumpdisplay_main_self[0]->_lf__clear),
    0);
    bumpdisplay_main_self[0]->_lf__clear.status = absent;
    bumpdisplay_main_self[0]->_lf__reaction_0.deadline = NEVER;
    bumpdisplay_main_self[0]->_lf__reaction_1.deadline = NEVER;
    bumpdisplay_main_self[0]->_lf__reaction_2.deadline = NEVER;
    {
        // ***** Start initializing BumpDisplay.bump of class Bump
        bumpdisplay_bump_self[0] = new__bump();
        bumpdisplay_bump_self[0]->base.environment = &envs[bumpdisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        bumpdisplay_bump_self[0]->sample_period = MSEC(100);
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_bump_self[0]->_lf_left_width = -2;
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_bump_self[0]->_lf_right_width = -2;
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_bump_self[0]->_lf_calibrate_width = -2;
        envs[bumpdisplay_main].startup_reactions[startup_reaction_count[bumpdisplay_main]++] = &bumpdisplay_bump_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        // Initiaizing timer BumpDisplay.bump.t1.
        bumpdisplay_bump_self[0]->_lf__t1.offset = 0;
        bumpdisplay_bump_self[0]->_lf__t1.period = MSEC(100);
        // Associate timer with the environment of its parent
        envs[bumpdisplay_main].timer_triggers[timer_triggers_count[bumpdisplay_main]++] = &bumpdisplay_bump_self[0]->_lf__t1;
        bumpdisplay_bump_self[0]->_lf__t1.mode = NULL;
    
        bumpdisplay_bump_self[0]->_lf__reaction_0.deadline = NEVER;
        bumpdisplay_bump_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing BumpDisplay.bump
    }
    {
        // ***** Start initializing BumpDisplay.disp of class Display
        bumpdisplay_disp_self[0] = new__display();
        bumpdisplay_disp_self[0]->base.environment = &envs[bumpdisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_disp_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_disp_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_disp_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_disp_self[0]->_lf_line3_width = -2;
        envs[bumpdisplay_main].startup_reactions[startup_reaction_count[bumpdisplay_main]++] = &bumpdisplay_disp_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        bumpdisplay_disp_self[0]->_lf__reaction_0.deadline = NEVER;
        bumpdisplay_disp_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing BumpDisplay.disp
    }
    //***** End initializing BumpDisplay
    // **** Start deferred initialize for BumpDisplay
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of BumpDisplay.
        bumpdisplay_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        bumpdisplay_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &bumpdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                bumpdisplay_main_self[0]->_lf__reaction_0.output_produced[count++] = &bumpdisplay_main_self[0]->_lf_disp.line0.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of BumpDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of BumpDisplay.
        bumpdisplay_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        bumpdisplay_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &bumpdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                bumpdisplay_main_self[0]->_lf__reaction_1.output_produced[count++] = &bumpdisplay_main_self[0]->_lf_disp.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of BumpDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of BumpDisplay.
        bumpdisplay_main_self[0]->_lf__reaction_2.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        bumpdisplay_main_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &bumpdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                bumpdisplay_main_self[0]->_lf__reaction_2.output_produced[count++] = &bumpdisplay_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                bumpdisplay_main_self[0]->_lf__reaction_2.output_produced[count++] = &bumpdisplay_main_self[0]->_lf_disp.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 2 of BumpDisplay
    
        // **** Start deferred initialize for BumpDisplay.bump
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of BumpDisplay.bump.
            bumpdisplay_bump_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of BumpDisplay.bump
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of BumpDisplay.bump.
            bumpdisplay_bump_self[0]->_lf__reaction_1.num_outputs = 2;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            bumpdisplay_bump_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    2, sizeof(trigger_t**),
                    &bumpdisplay_bump_self[0]->base.allocations);
            bumpdisplay_bump_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    2, sizeof(int),
                    &bumpdisplay_bump_self[0]->base.allocations);
            bumpdisplay_bump_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    2, sizeof(bool*),
                    &bumpdisplay_bump_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    bumpdisplay_bump_self[0]->_lf__reaction_1.output_produced[count++] = &bumpdisplay_bump_self[0]->_lf_left.is_present;
                }
                {
                    bumpdisplay_bump_self[0]->_lf__reaction_1.output_produced[count++] = &bumpdisplay_bump_self[0]->_lf_right.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of BumpDisplay.bump
        
        }
        // **** End of deferred initialize for BumpDisplay.bump
        // **** Start deferred initialize for BumpDisplay.disp
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of BumpDisplay.disp.
            bumpdisplay_disp_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of BumpDisplay.disp
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of BumpDisplay.disp.
            bumpdisplay_disp_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of BumpDisplay.disp
        
        }
        // **** End of deferred initialize for BumpDisplay.disp
    }
    // **** End of deferred initialize for BumpDisplay
    // **** Start non-nested deferred initialize for BumpDisplay
    // Set number of destination reactors for port disp.line0.
    // Iterate over range BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        bumpdisplay_main_self[src_runtime]->_lf_disp.line0._base.num_destinations = 1;
        bumpdisplay_main_self[src_runtime]->_lf_disp.line0._base.source_reactor = (self_base_t*)bumpdisplay_main_self[src_runtime];
    }
    // Set number of destination reactors for port disp.line1.
    // Iterate over range BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        bumpdisplay_main_self[src_runtime]->_lf_disp.line1._base.num_destinations = 1;
        bumpdisplay_main_self[src_runtime]->_lf_disp.line1._base.source_reactor = (self_base_t*)bumpdisplay_main_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of BumpDisplay triggers 1 downstream reactions
            // through port BumpDisplay.disp.line0.
            bumpdisplay_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of BumpDisplay, allocate an
            // array of trigger pointers for downstream reactions through port BumpDisplay.disp.line0
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bumpdisplay_main_self[src_runtime]->base.allocations); 
            bumpdisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)] and BumpDisplay.disp.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range BumpDisplay.disp.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port BumpDisplay.disp.line0's trigger struct.
                bumpdisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_disp_self[dst_runtime]->_lf__line0;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of BumpDisplay triggers 1 downstream reactions
            // through port BumpDisplay.disp.line1.
            bumpdisplay_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of BumpDisplay, allocate an
            // array of trigger pointers for downstream reactions through port BumpDisplay.disp.line1
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bumpdisplay_main_self[src_runtime]->base.allocations); 
            bumpdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)] and BumpDisplay.disp.line1(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range BumpDisplay.disp.line1(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port BumpDisplay.disp.line1's trigger struct.
                bumpdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_disp_self[dst_runtime]->_lf__line1;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of BumpDisplay triggers 1 downstream reactions
            // through port BumpDisplay.disp.line0.
            bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of BumpDisplay, allocate an
            // array of trigger pointers for downstream reactions through port BumpDisplay.disp.line0
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bumpdisplay_main_self[src_runtime]->base.allocations); 
            bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of BumpDisplay triggers 1 downstream reactions
            // through port BumpDisplay.disp.line1.
            bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of BumpDisplay, allocate an
            // array of trigger pointers for downstream reactions through port BumpDisplay.disp.line1
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bumpdisplay_main_self[src_runtime]->base.allocations); 
            bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)] and BumpDisplay.disp.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range BumpDisplay.disp.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port BumpDisplay.disp.line0's trigger struct.
                bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_disp_self[dst_runtime]->_lf__line0;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)] and BumpDisplay.disp.line1(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range BumpDisplay.disp.line1(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port BumpDisplay.disp.line1's trigger struct.
                bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_disp_self[dst_runtime]->_lf__line1;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for BumpDisplay.bump
    
    // For reference counting, set num_destinations for port BumpDisplay.bump.left.
    // Iterate over range BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        bumpdisplay_bump_self[src_runtime]->_lf_left._base.num_destinations = 1;
        bumpdisplay_bump_self[src_runtime]->_lf_left._base.source_reactor = (self_base_t*)bumpdisplay_bump_self[src_runtime];
    }
    // For reference counting, set num_destinations for port BumpDisplay.bump.right.
    // Iterate over range BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        bumpdisplay_bump_self[src_runtime]->_lf_right._base.num_destinations = 1;
        bumpdisplay_bump_self[src_runtime]->_lf_right._base.source_reactor = (self_base_t*)bumpdisplay_bump_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of BumpDisplay.bump triggers 1 downstream reactions
            // through port BumpDisplay.bump.left.
            bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of BumpDisplay.bump, allocate an
            // array of trigger pointers for downstream reactions through port BumpDisplay.bump.left
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bumpdisplay_bump_self[src_runtime]->base.allocations); 
            bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of BumpDisplay.bump triggers 1 downstream reactions
            // through port BumpDisplay.bump.right.
            bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of BumpDisplay.bump, allocate an
            // array of trigger pointers for downstream reactions through port BumpDisplay.bump.right
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bumpdisplay_bump_self[src_runtime]->base.allocations); 
            bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)] and BumpDisplay.bump.left(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range BumpDisplay.bump.left(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port BumpDisplay.bump.left has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_main_self[dst_runtime]->_lf_bump.left_trigger;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)] and BumpDisplay.bump.right(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range BumpDisplay.bump.right(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port BumpDisplay.bump.right has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_main_self[dst_runtime]->_lf_bump.right_trigger;
            }
        }
    }
    
    // **** End of non-nested deferred initialize for BumpDisplay.bump
    // **** Start non-nested deferred initialize for BumpDisplay.disp
    
    
    
    
    // **** End of non-nested deferred initialize for BumpDisplay.disp
    // **** End of non-nested deferred initialize for BumpDisplay
    // Connect inputs and outputs for reactor BumpDisplay.
    // Connect inputs and outputs for reactor BumpDisplay.bump.
    // Connect BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)] to port BumpDisplay.bump.left(0,1)
    // Iterate over ranges BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)] and BumpDisplay.bump.left(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range BumpDisplay.bump.left(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_main_self[dst_runtime]->_lf_bump.left = (_bump_left_t*)&bumpdisplay_bump_self[src_runtime]->_lf_left;
        }
    }
    // Connect BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)] to port BumpDisplay.bump.right(0,1)
    // Iterate over ranges BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)] and BumpDisplay.bump.right(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range BumpDisplay.bump.right(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_main_self[dst_runtime]->_lf_bump.right = (_bump_right_t*)&bumpdisplay_bump_self[src_runtime]->_lf_right;
        }
    }
    // Connect inputs and outputs for reactor BumpDisplay.disp.
    // Connect BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)] to port BumpDisplay.disp.line0(0,1)
    // Iterate over ranges BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)] and BumpDisplay.disp.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range BumpDisplay.disp.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_disp_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&bumpdisplay_main_self[src_runtime]->_lf_disp.line0;
        }
    }
    // Connect BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)] to port BumpDisplay.disp.line1(0,1)
    // Iterate over ranges BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)] and BumpDisplay.disp.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range BumpDisplay.disp.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_disp_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&bumpdisplay_main_self[src_runtime]->_lf_disp.line1;
        }
    }
    {
    }
    {
    }
    // Add port BumpDisplay.disp.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[bumpdisplay_main].is_present_fields[0 + count] = &bumpdisplay_main_self[0]->_lf_disp.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[bumpdisplay_main]._lf_intended_tag_fields[0 + count] = &bumpdisplay_main_self[0]->_lf_disp.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port BumpDisplay.disp.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[bumpdisplay_main].is_present_fields[1 + count] = &bumpdisplay_main_self[0]->_lf_disp.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[bumpdisplay_main]._lf_intended_tag_fields[1 + count] = &bumpdisplay_main_self[0]->_lf_disp.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action BumpDisplay.clear to array of is_present fields.
        envs[bumpdisplay_main].is_present_fields[2] 
                = &bumpdisplay_main_self[0]->_lf_clear.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action BumpDisplay.clear to array of intended_tag fields.
        envs[bumpdisplay_main]._lf_intended_tag_fields[2] 
                = &bumpdisplay_main_self[0]->_lf_clear.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port BumpDisplay.bump.left to array of is_present fields.
            envs[bumpdisplay_main].is_present_fields[3 + count] = &bumpdisplay_bump_self[0]->_lf_left.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port BumpDisplay.bump.left to array of intended_tag fields.
            envs[bumpdisplay_main]._lf_intended_tag_fields[3 + count] = &bumpdisplay_bump_self[0]->_lf_left.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port BumpDisplay.bump.right to array of is_present fields.
            envs[bumpdisplay_main].is_present_fields[3 + count] = &bumpdisplay_bump_self[0]->_lf_right.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port BumpDisplay.bump.right to array of intended_tag fields.
            envs[bumpdisplay_main]._lf_intended_tag_fields[3 + count] = &bumpdisplay_bump_self[0]->_lf_right.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance BumpDisplay
    {
        bumpdisplay_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bumpdisplay_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0002LL;
        bumpdisplay_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 3 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bumpdisplay_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0003LL;
        bumpdisplay_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 4 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bumpdisplay_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0004LL;
    
        // Set reaction priorities for ReactorInstance BumpDisplay.bump
        {
            bumpdisplay_bump_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bumpdisplay_bump_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            bumpdisplay_bump_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bumpdisplay_bump_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    
        // Set reaction priorities for ReactorInstance BumpDisplay.disp
        {
            bumpdisplay_disp_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bumpdisplay_disp_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            bumpdisplay_disp_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 5 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bumpdisplay_disp_self[0]->_lf__reaction_1.index = 0xffffffffffff0005LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
