// Code generated by the Lingua Franca compiler from:
// file://mnt/c/Users/gyoe4/EECS149Proj/PololuCharacterization/src/RobotTemplate.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void lf_set_default_command_line_options() {}
#include "_robot.h"
#include "_display.h"
#include "_robottemplate_main.h"
typedef enum {
    robottemplate_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&envs[robottemplate_main],"RobotTemplate",robottemplate_main,_lf_number_of_workers,1,2,0,0,2,1,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _robottemplate_main_main_self_t* robottemplate_main_self[1];
    SUPPRESS_UNUSED_WARNING(robottemplate_main_self);
    _robot_self_t* robottemplate_robot_self[1];
    SUPPRESS_UNUSED_WARNING(robottemplate_robot_self);
    _display_self_t* robottemplate_display_self[1];
    SUPPRESS_UNUSED_WARNING(robottemplate_display_self);
    // ***** Start initializing RobotTemplate of class RobotTemplate
    robottemplate_main_self[0] = new__robottemplate_main();
    robottemplate_main_self[0]->base.environment = &envs[robottemplate_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    { // For scoping
        static bool _initial = false;
        robottemplate_main_self[0]->drive = _initial;
    } // End scoping.
    // Initiaizing timer RobotTemplate.t.
    robottemplate_main_self[0]->_lf__t.offset = 0;
    robottemplate_main_self[0]->_lf__t.period = SEC(2);
    // Associate timer with the environment of its parent
    envs[robottemplate_main].timer_triggers[timer_triggers_count[robottemplate_main]++] = &robottemplate_main_self[0]->_lf__t;
    robottemplate_main_self[0]->_lf__t.mode = NULL;
    
    robottemplate_main_self[0]->_lf__reaction_0.deadline = NEVER;
    {
        _robottemplate_main_main_self_t *self = robottemplate_main_self[0];
        // ***** Start initializing RobotTemplate.robot of class Robot
        robottemplate_robot_self[0] = new__robot();
        robottemplate_robot_self[0]->base.environment = &envs[robottemplate_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        robottemplate_robot_self[0]->_lf_notify_width = -2;
        // width of -2 indicates that it is not a multiport.
        robottemplate_robot_self[0]->_lf_drive_width = -2;
        envs[robottemplate_main].startup_reactions[startup_reaction_count[robottemplate_main]++] = &robottemplate_robot_self[0]->_lf__reaction_0;
    
        robottemplate_robot_self[0]->_lf__reaction_0.deadline = NEVER;
        robottemplate_robot_self[0]->_lf__reaction_1.deadline = NEVER;
        robottemplate_robot_self[0]->_lf__reaction_2.deadline = NEVER;
        // Register for transition handling
        envs[robottemplate_main].modes->modal_reactor_states[modal_reactor_count[robottemplate_main]++] = &((self_base_t*)robottemplate_robot_self[0])->_lf__mode_state;
        //***** End initializing RobotTemplate.robot
    }
    {
        _robottemplate_main_main_self_t *self = robottemplate_main_self[0];
        // ***** Start initializing RobotTemplate.display of class Display
        robottemplate_display_self[0] = new__display();
        robottemplate_display_self[0]->base.environment = &envs[robottemplate_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        robottemplate_display_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        robottemplate_display_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        robottemplate_display_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        robottemplate_display_self[0]->_lf_line3_width = -2;
        envs[robottemplate_main].startup_reactions[startup_reaction_count[robottemplate_main]++] = &robottemplate_display_self[0]->_lf__reaction_0;
    
        robottemplate_display_self[0]->_lf__reaction_0.deadline = NEVER;
        robottemplate_display_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing RobotTemplate.display
    }
    //***** End initializing RobotTemplate
    // **** Start deferred initialize for RobotTemplate
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of RobotTemplate.
        robottemplate_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        robottemplate_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                1, sizeof(trigger_t**),
                &robottemplate_main_self[0]->base.allocations);
        robottemplate_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                1, sizeof(int),
                &robottemplate_main_self[0]->base.allocations);
        robottemplate_main_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                1, sizeof(bool*),
                &robottemplate_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                robottemplate_main_self[0]->_lf__reaction_0.output_produced[count++] = &robottemplate_main_self[0]->_lf_robot.drive.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of RobotTemplate
    
        // **** Start deferred initialize for RobotTemplate.robot
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of RobotTemplate.robot.
            robottemplate_robot_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robottemplate_robot_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &robottemplate_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robottemplate_robot_self[0]->_lf__reaction_0.output_produced[count++] = &robottemplate_robot_self[0]->_lf_notify.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of RobotTemplate.robot
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of RobotTemplate.robot.
            robottemplate_robot_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robottemplate_robot_self[0]->_lf__reaction_1.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_1.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_1.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &robottemplate_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robottemplate_robot_self[0]->_lf__reaction_1.output_produced[count++] = &robottemplate_robot_self[0]->_lf_notify.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of RobotTemplate.robot
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of RobotTemplate.robot.
            robottemplate_robot_self[0]->_lf__reaction_2.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robottemplate_robot_self[0]->_lf__reaction_2.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_2.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_2.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &robottemplate_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robottemplate_robot_self[0]->_lf__reaction_2.output_produced[count++] = &robottemplate_robot_self[0]->_lf_notify.is_present;
                }
            }
            
            // ** End initialization for reaction 2 of RobotTemplate.robot
        
        }
        // **** End of deferred initialize for RobotTemplate.robot
        // **** Start deferred initialize for RobotTemplate.display
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of RobotTemplate.display.
            robottemplate_display_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of RobotTemplate.display
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of RobotTemplate.display.
            robottemplate_display_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of RobotTemplate.display
        
        }
        // **** End of deferred initialize for RobotTemplate.display
    }
    // **** End of deferred initialize for RobotTemplate
    // **** Start non-nested deferred initialize for RobotTemplate
    {
        // Set number of destination reactors for port robot.drive.
        // Iterate over range RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robottemplate_main_self[src_runtime]->_lf_robot.drive._base.num_destinations = 1;
            robottemplate_main_self[src_runtime]->_lf_robot.drive._base.source_reactor = (self_base_t*)robottemplate_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of RobotTemplate triggers 1 downstream reactions
                // through port RobotTemplate.robot.drive.
                robottemplate_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of RobotTemplate, allocate an
                // array of trigger pointers for downstream reactions through port RobotTemplate.robot.drive
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &robottemplate_main_self[src_runtime]->base.allocations); 
                robottemplate_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)] and RobotTemplate.robot.drive(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotTemplate.robot.drive(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotTemplate.robot.drive's trigger struct.
                    robottemplate_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &robottemplate_robot_self[dst_runtime]->_lf__drive;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for RobotTemplate.robot
        {
        
            // For reference counting, set num_destinations for port RobotTemplate.robot.notify.
            // Iterate over range RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                robottemplate_robot_self[src_runtime]->_lf_notify._base.num_destinations = 1;
                robottemplate_robot_self[src_runtime]->_lf_notify._base.source_reactor = (self_base_t*)robottemplate_robot_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.line0(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of RobotTemplate.robot triggers 1 downstream reactions
                    // through port RobotTemplate.robot.notify.
                    robottemplate_robot_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of RobotTemplate.robot, allocate an
                    // array of trigger pointers for downstream reactions through port RobotTemplate.robot.notify
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &robottemplate_robot_self[src_runtime]->base.allocations); 
                    robottemplate_robot_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.line0(0,1)] and RobotTemplate.display.line0(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range RobotTemplate.display.line0(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port RobotTemplate.display.line0's trigger struct.
                        robottemplate_robot_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &robottemplate_display_self[dst_runtime]->_lf__line0;
                    }
                }
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.line0(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of RobotTemplate.robot triggers 1 downstream reactions
                    // through port RobotTemplate.robot.notify.
                    robottemplate_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of RobotTemplate.robot, allocate an
                    // array of trigger pointers for downstream reactions through port RobotTemplate.robot.notify
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &robottemplate_robot_self[src_runtime]->base.allocations); 
                    robottemplate_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.line0(0,1)] and RobotTemplate.display.line0(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range RobotTemplate.display.line0(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port RobotTemplate.display.line0's trigger struct.
                        robottemplate_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &robottemplate_display_self[dst_runtime]->_lf__line0;
                    }
                }
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.line0(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 2 of RobotTemplate.robot triggers 1 downstream reactions
                    // through port RobotTemplate.robot.notify.
                    robottemplate_robot_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 2 of RobotTemplate.robot, allocate an
                    // array of trigger pointers for downstream reactions through port RobotTemplate.robot.notify
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &robottemplate_robot_self[src_runtime]->base.allocations); 
                    robottemplate_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.line0(0,1)] and RobotTemplate.display.line0(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range RobotTemplate.display.line0(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port RobotTemplate.display.line0's trigger struct.
                        robottemplate_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &robottemplate_display_self[dst_runtime]->_lf__line0;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for RobotTemplate.robot
        // **** Start non-nested deferred initialize for RobotTemplate.display
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for RobotTemplate.display
    }
    // **** End of non-nested deferred initialize for RobotTemplate
    // Connect inputs and outputs for reactor RobotTemplate.
    // Connect inputs and outputs for reactor RobotTemplate.robot.
    // Connect RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)] to port RobotTemplate.robot.drive(0,1)
    // Iterate over ranges RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)] and RobotTemplate.robot.drive(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotTemplate.robot.drive(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robottemplate_robot_self[dst_runtime]->_lf_drive = (_robot_drive_t*)&robottemplate_main_self[src_runtime]->_lf_robot.drive;
        }
    }
    // Connect RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.line0(0,1)] to port RobotTemplate.display.line0(0,1)
    // Iterate over ranges RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.line0(0,1)] and RobotTemplate.display.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotTemplate.display.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robottemplate_display_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&robottemplate_robot_self[src_runtime]->_lf_notify;
        }
    }
    // Connect inputs and outputs for reactor RobotTemplate.display.
    {
    }
    {
    }
    // Add port RobotTemplate.robot.drive to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[robottemplate_main].is_present_fields[0 + (0) * 1 + count] = &robottemplate_main_self[0]->_lf_robot.drive.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[robottemplate_main]._lf_intended_tag_fields[0 + (0) * 1 + count] = &robottemplate_main_self[0]->_lf_robot.drive.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port RobotTemplate.robot.notify to array of is_present fields.
            envs[robottemplate_main].is_present_fields[(0) * 1 + 1 + count] = &robottemplate_robot_self[0]->_lf_notify.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port RobotTemplate.robot.notify to array of intended_tag fields.
            envs[robottemplate_main]._lf_intended_tag_fields[(0) * 1 + 1 + count] = &robottemplate_robot_self[0]->_lf_notify.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance RobotTemplate
    {
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        robottemplate_main_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
    
        // Set reaction priorities for ReactorInstance RobotTemplate.robot
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robottemplate_robot_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robottemplate_robot_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 1);
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robottemplate_robot_self[0]->_lf__reaction_2.index = lf_combine_deadline_and_level(9223372036854775807, 2);
        }
    
    
        // Set reaction priorities for ReactorInstance RobotTemplate.display
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robottemplate_display_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robottemplate_display_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 3);
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
