// Code generated by the Lingua Franca compiler from:
// file://home/foobar/EECS149Proj/PololuCharacterization/src/RobotDriveSolution.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/EECS149Proj/PololuCharacterization/src-gen/RobotDriveSolution"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_motors.h"
#include "_robot.h"
#include "_display.h"
#include "_robotdrivesolution_main.h"
typedef enum {
    robotdrivesolution_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[robotdrivesolution_main],robotdrivesolution_main,_lf_number_of_workers,1,3,0,0,4,1,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _robotdrivesolution_main_main_self_t* robotdrivesolution_main_self[1];
    SUPPRESS_UNUSED_WARNING(robotdrivesolution_main_self);
    _robot_self_t* robotdrivesolution_robot_self[1];
    SUPPRESS_UNUSED_WARNING(robotdrivesolution_robot_self);
    _motors_self_t* robotdrivesolution_robot_motors_self[1];
    SUPPRESS_UNUSED_WARNING(robotdrivesolution_robot_motors_self);
    _display_self_t* robotdrivesolution_display_self[1];
    SUPPRESS_UNUSED_WARNING(robotdrivesolution_display_self);
    // ***** Start initializing RobotDriveSolution of class RobotDriveSolution
    robotdrivesolution_main_self[0] = new__robotdrivesolution_main();
    robotdrivesolution_main_self[0]->base.environment = &envs[robotdrivesolution_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    { // For scoping
        static bool _initial = false;
        robotdrivesolution_main_self[0]->drive = _initial;
    } // End scoping.
    // Initiaizing timer RobotDriveSolution.t.
    robotdrivesolution_main_self[0]->_lf__t.offset = 0;
    robotdrivesolution_main_self[0]->_lf__t.period = SEC(2);
    // Associate timer with the environment of its parent
    envs[robotdrivesolution_main].timer_triggers[timer_triggers_count[robotdrivesolution_main]++] = &robotdrivesolution_main_self[0]->_lf__t;
    robotdrivesolution_main_self[0]->_lf__t.mode = NULL;
    
    robotdrivesolution_main_self[0]->_lf__reaction_0.deadline = NEVER;
    {
        // ***** Start initializing RobotDriveSolution.robot of class Robot
        robotdrivesolution_robot_self[0] = new__robot();
        robotdrivesolution_robot_self[0]->base.environment = &envs[robotdrivesolution_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        robotdrivesolution_robot_self[0]->_lf_notify_width = -2;
        // width of -2 indicates that it is not a multiport.
        robotdrivesolution_robot_self[0]->_lf_drive_width = -2;
        envs[robotdrivesolution_main].startup_reactions[startup_reaction_count[robotdrivesolution_main]++] = &robotdrivesolution_robot_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        robotdrivesolution_robot_self[0]->_lf__reaction_0.deadline = NEVER;
        robotdrivesolution_robot_self[0]->_lf__reaction_1.deadline = NEVER;
        robotdrivesolution_robot_self[0]->_lf__reaction_2.deadline = NEVER;
        // Register for transition handling
        envs[robotdrivesolution_main].modes->modal_reactor_states[modal_reactor_count[robotdrivesolution_main]++] = &((self_base_t*)robotdrivesolution_robot_self[0])->_lf__mode_state;
        {
            // ***** Start initializing RobotDriveSolution.robot.motors of class Motors
            robotdrivesolution_robot_motors_self[0] = new__motors();
            robotdrivesolution_robot_motors_self[0]->base.environment = &envs[robotdrivesolution_main];
            bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
            // width of -2 indicates that it is not a multiport.
            robotdrivesolution_robot_motors_self[0]->_lf_left_power_width = -2;
            // width of -2 indicates that it is not a multiport.
            robotdrivesolution_robot_motors_self[0]->_lf_right_power_width = -2;
            envs[robotdrivesolution_main].startup_reactions[startup_reaction_count[robotdrivesolution_main]++] = &robotdrivesolution_robot_motors_self[0]->_lf__reaction_0;
            SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
            robotdrivesolution_robot_motors_self[0]->_lf__reaction_0.deadline = NEVER;
            robotdrivesolution_robot_motors_self[0]->_lf__reaction_1.deadline = NEVER;
            robotdrivesolution_robot_motors_self[0]->_lf__reaction_2.deadline = NEVER;
            //***** End initializing RobotDriveSolution.robot.motors
        }
        //***** End initializing RobotDriveSolution.robot
    }
    {
        // ***** Start initializing RobotDriveSolution.display of class Display
        robotdrivesolution_display_self[0] = new__display();
        robotdrivesolution_display_self[0]->base.environment = &envs[robotdrivesolution_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        robotdrivesolution_display_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        robotdrivesolution_display_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        robotdrivesolution_display_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        robotdrivesolution_display_self[0]->_lf_line3_width = -2;
        envs[robotdrivesolution_main].startup_reactions[startup_reaction_count[robotdrivesolution_main]++] = &robotdrivesolution_display_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        robotdrivesolution_display_self[0]->_lf__reaction_0.deadline = NEVER;
        robotdrivesolution_display_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing RobotDriveSolution.display
    }
    //***** End initializing RobotDriveSolution
    // **** Start deferred initialize for RobotDriveSolution
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of RobotDriveSolution.
        robotdrivesolution_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        robotdrivesolution_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &robotdrivesolution_main_self[0]->base.allocations);
        robotdrivesolution_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &robotdrivesolution_main_self[0]->base.allocations);
        robotdrivesolution_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &robotdrivesolution_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                robotdrivesolution_main_self[0]->_lf__reaction_0.output_produced[count++] = &robotdrivesolution_main_self[0]->_lf_robot.drive.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of RobotDriveSolution
    
        // **** Start deferred initialize for RobotDriveSolution.robot
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of RobotDriveSolution.robot.
            robotdrivesolution_robot_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robotdrivesolution_robot_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &robotdrivesolution_robot_self[0]->base.allocations);
            robotdrivesolution_robot_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &robotdrivesolution_robot_self[0]->base.allocations);
            robotdrivesolution_robot_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &robotdrivesolution_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robotdrivesolution_robot_self[0]->_lf__reaction_0.output_produced[count++] = &robotdrivesolution_robot_self[0]->_lf_notify.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of RobotDriveSolution.robot
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of RobotDriveSolution.robot.
            robotdrivesolution_robot_self[0]->_lf__reaction_1.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robotdrivesolution_robot_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &robotdrivesolution_robot_self[0]->base.allocations);
            robotdrivesolution_robot_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &robotdrivesolution_robot_self[0]->base.allocations);
            robotdrivesolution_robot_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &robotdrivesolution_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robotdrivesolution_robot_self[0]->_lf__reaction_1.output_produced[count++] = &robotdrivesolution_robot_self[0]->_lf_notify.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    robotdrivesolution_robot_self[0]->_lf__reaction_1.output_produced[count++] = &robotdrivesolution_robot_self[0]->_lf_motors.left_power.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    robotdrivesolution_robot_self[0]->_lf__reaction_1.output_produced[count++] = &robotdrivesolution_robot_self[0]->_lf_motors.right_power.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of RobotDriveSolution.robot
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of RobotDriveSolution.robot.
            robotdrivesolution_robot_self[0]->_lf__reaction_2.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robotdrivesolution_robot_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &robotdrivesolution_robot_self[0]->base.allocations);
            robotdrivesolution_robot_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &robotdrivesolution_robot_self[0]->base.allocations);
            robotdrivesolution_robot_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &robotdrivesolution_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robotdrivesolution_robot_self[0]->_lf__reaction_2.output_produced[count++] = &robotdrivesolution_robot_self[0]->_lf_notify.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    robotdrivesolution_robot_self[0]->_lf__reaction_2.output_produced[count++] = &robotdrivesolution_robot_self[0]->_lf_motors.left_power.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    robotdrivesolution_robot_self[0]->_lf__reaction_2.output_produced[count++] = &robotdrivesolution_robot_self[0]->_lf_motors.right_power.is_present;
                }
            }
            
            // ** End initialization for reaction 2 of RobotDriveSolution.robot
        
            // **** Start deferred initialize for RobotDriveSolution.robot.motors
            {
            
                // Total number of outputs (single ports and multiport channels)
                // produced by reaction_0 of RobotDriveSolution.robot.motors.
                robotdrivesolution_robot_motors_self[0]->_lf__reaction_0.num_outputs = 0;
                {
                    int count = 0; SUPPRESS_UNUSED_WARNING(count);
                }
                
                // ** End initialization for reaction 0 of RobotDriveSolution.robot.motors
                // Total number of outputs (single ports and multiport channels)
                // produced by reaction_1 of RobotDriveSolution.robot.motors.
                robotdrivesolution_robot_motors_self[0]->_lf__reaction_1.num_outputs = 0;
                {
                    int count = 0; SUPPRESS_UNUSED_WARNING(count);
                }
                
                // ** End initialization for reaction 1 of RobotDriveSolution.robot.motors
                // Total number of outputs (single ports and multiport channels)
                // produced by reaction_2 of RobotDriveSolution.robot.motors.
                robotdrivesolution_robot_motors_self[0]->_lf__reaction_2.num_outputs = 0;
                {
                    int count = 0; SUPPRESS_UNUSED_WARNING(count);
                }
                
                // ** End initialization for reaction 2 of RobotDriveSolution.robot.motors
            
            }
            // **** End of deferred initialize for RobotDriveSolution.robot.motors
        }
        // **** End of deferred initialize for RobotDriveSolution.robot
        // **** Start deferred initialize for RobotDriveSolution.display
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of RobotDriveSolution.display.
            robotdrivesolution_display_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of RobotDriveSolution.display
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of RobotDriveSolution.display.
            robotdrivesolution_display_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of RobotDriveSolution.display
        
        }
        // **** End of deferred initialize for RobotDriveSolution.display
    }
    // **** End of deferred initialize for RobotDriveSolution
    // **** Start non-nested deferred initialize for RobotDriveSolution
    // Set number of destination reactors for port robot.drive.
    // Iterate over range RobotDriveSolution.robot.drive(0,1)->[RobotDriveSolution.robot.drive(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        robotdrivesolution_main_self[src_runtime]->_lf_robot.drive._base.num_destinations = 1;
        robotdrivesolution_main_self[src_runtime]->_lf_robot.drive._base.source_reactor = (self_base_t*)robotdrivesolution_main_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range RobotDriveSolution.robot.drive(0,1)->[RobotDriveSolution.robot.drive(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of RobotDriveSolution triggers 1 downstream reactions
            // through port RobotDriveSolution.robot.drive.
            robotdrivesolution_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of RobotDriveSolution, allocate an
            // array of trigger pointers for downstream reactions through port RobotDriveSolution.robot.drive
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robotdrivesolution_main_self[src_runtime]->base.allocations); 
            robotdrivesolution_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges RobotDriveSolution.robot.drive(0,1)->[RobotDriveSolution.robot.drive(0,1)] and RobotDriveSolution.robot.drive(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotDriveSolution.robot.drive(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotDriveSolution.robot.drive's trigger struct.
                robotdrivesolution_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &robotdrivesolution_robot_self[dst_runtime]->_lf__drive;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for RobotDriveSolution.robot
    // Set number of destination reactors for port motors.left_power.
    // Iterate over range RobotDriveSolution.robot.motors.left_power(0,1)->[RobotDriveSolution.robot.motors.left_power(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        robotdrivesolution_robot_self[src_runtime]->_lf_motors.left_power._base.num_destinations = 1;
        robotdrivesolution_robot_self[src_runtime]->_lf_motors.left_power._base.source_reactor = (self_base_t*)robotdrivesolution_robot_self[src_runtime];
    }
    // Set number of destination reactors for port motors.right_power.
    // Iterate over range RobotDriveSolution.robot.motors.right_power(0,1)->[RobotDriveSolution.robot.motors.right_power(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        robotdrivesolution_robot_self[src_runtime]->_lf_motors.right_power._base.num_destinations = 1;
        robotdrivesolution_robot_self[src_runtime]->_lf_motors.right_power._base.source_reactor = (self_base_t*)robotdrivesolution_robot_self[src_runtime];
    }
    // For reference counting, set num_destinations for port RobotDriveSolution.robot.notify.
    // Iterate over range RobotDriveSolution.robot.notify(0,1)->[RobotDriveSolution.display.line0(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        robotdrivesolution_robot_self[src_runtime]->_lf_notify._base.num_destinations = 1;
        robotdrivesolution_robot_self[src_runtime]->_lf_notify._base.source_reactor = (self_base_t*)robotdrivesolution_robot_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range RobotDriveSolution.robot.notify(0,1)->[RobotDriveSolution.display.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of RobotDriveSolution.robot triggers 1 downstream reactions
            // through port RobotDriveSolution.robot.notify.
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of RobotDriveSolution.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotDriveSolution.robot.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robotdrivesolution_robot_self[src_runtime]->base.allocations); 
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges RobotDriveSolution.robot.notify(0,1)->[RobotDriveSolution.display.line0(0,1)] and RobotDriveSolution.display.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotDriveSolution.display.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotDriveSolution.display.line0's trigger struct.
                robotdrivesolution_robot_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &robotdrivesolution_display_self[dst_runtime]->_lf__line0;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range RobotDriveSolution.robot.notify(0,1)->[RobotDriveSolution.display.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of RobotDriveSolution.robot triggers 1 downstream reactions
            // through port RobotDriveSolution.robot.notify.
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of RobotDriveSolution.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotDriveSolution.robot.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robotdrivesolution_robot_self[src_runtime]->base.allocations); 
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range RobotDriveSolution.robot.motors.left_power(0,1)->[RobotDriveSolution.robot.motors.left_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of RobotDriveSolution.robot triggers 1 downstream reactions
            // through port RobotDriveSolution.robot.motors.left_power.
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of RobotDriveSolution.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotDriveSolution.robot.motors.left_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robotdrivesolution_robot_self[src_runtime]->base.allocations); 
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range RobotDriveSolution.robot.motors.right_power(0,1)->[RobotDriveSolution.robot.motors.right_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of RobotDriveSolution.robot triggers 1 downstream reactions
            // through port RobotDriveSolution.robot.motors.right_power.
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of RobotDriveSolution.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotDriveSolution.robot.motors.right_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robotdrivesolution_robot_self[src_runtime]->base.allocations); 
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges RobotDriveSolution.robot.notify(0,1)->[RobotDriveSolution.display.line0(0,1)] and RobotDriveSolution.display.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotDriveSolution.display.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotDriveSolution.display.line0's trigger struct.
                robotdrivesolution_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &robotdrivesolution_display_self[dst_runtime]->_lf__line0;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges RobotDriveSolution.robot.motors.left_power(0,1)->[RobotDriveSolution.robot.motors.left_power(0,1)] and RobotDriveSolution.robot.motors.left_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotDriveSolution.robot.motors.left_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotDriveSolution.robot.motors.left_power's trigger struct.
                robotdrivesolution_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &robotdrivesolution_robot_motors_self[dst_runtime]->_lf__left_power;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges RobotDriveSolution.robot.motors.right_power(0,1)->[RobotDriveSolution.robot.motors.right_power(0,1)] and RobotDriveSolution.robot.motors.right_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotDriveSolution.robot.motors.right_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotDriveSolution.robot.motors.right_power's trigger struct.
                robotdrivesolution_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &robotdrivesolution_robot_motors_self[dst_runtime]->_lf__right_power;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range RobotDriveSolution.robot.notify(0,1)->[RobotDriveSolution.display.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of RobotDriveSolution.robot triggers 1 downstream reactions
            // through port RobotDriveSolution.robot.notify.
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of RobotDriveSolution.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotDriveSolution.robot.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robotdrivesolution_robot_self[src_runtime]->base.allocations); 
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range RobotDriveSolution.robot.motors.left_power(0,1)->[RobotDriveSolution.robot.motors.left_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of RobotDriveSolution.robot triggers 1 downstream reactions
            // through port RobotDriveSolution.robot.motors.left_power.
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of RobotDriveSolution.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotDriveSolution.robot.motors.left_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robotdrivesolution_robot_self[src_runtime]->base.allocations); 
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range RobotDriveSolution.robot.motors.right_power(0,1)->[RobotDriveSolution.robot.motors.right_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of RobotDriveSolution.robot triggers 1 downstream reactions
            // through port RobotDriveSolution.robot.motors.right_power.
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of RobotDriveSolution.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotDriveSolution.robot.motors.right_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robotdrivesolution_robot_self[src_runtime]->base.allocations); 
            robotdrivesolution_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges RobotDriveSolution.robot.notify(0,1)->[RobotDriveSolution.display.line0(0,1)] and RobotDriveSolution.display.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotDriveSolution.display.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotDriveSolution.display.line0's trigger struct.
                robotdrivesolution_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &robotdrivesolution_display_self[dst_runtime]->_lf__line0;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges RobotDriveSolution.robot.motors.left_power(0,1)->[RobotDriveSolution.robot.motors.left_power(0,1)] and RobotDriveSolution.robot.motors.left_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotDriveSolution.robot.motors.left_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotDriveSolution.robot.motors.left_power's trigger struct.
                robotdrivesolution_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &robotdrivesolution_robot_motors_self[dst_runtime]->_lf__left_power;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges RobotDriveSolution.robot.motors.right_power(0,1)->[RobotDriveSolution.robot.motors.right_power(0,1)] and RobotDriveSolution.robot.motors.right_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotDriveSolution.robot.motors.right_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotDriveSolution.robot.motors.right_power's trigger struct.
                robotdrivesolution_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &robotdrivesolution_robot_motors_self[dst_runtime]->_lf__right_power;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for RobotDriveSolution.robot.motors
    
    
    
    
    // **** End of non-nested deferred initialize for RobotDriveSolution.robot.motors
    // **** End of non-nested deferred initialize for RobotDriveSolution.robot
    // **** Start non-nested deferred initialize for RobotDriveSolution.display
    
    
    
    
    // **** End of non-nested deferred initialize for RobotDriveSolution.display
    // **** End of non-nested deferred initialize for RobotDriveSolution
    // Connect inputs and outputs for reactor RobotDriveSolution.
    // Connect inputs and outputs for reactor RobotDriveSolution.robot.
    // Connect RobotDriveSolution.robot.drive(0,1)->[RobotDriveSolution.robot.drive(0,1)] to port RobotDriveSolution.robot.drive(0,1)
    // Iterate over ranges RobotDriveSolution.robot.drive(0,1)->[RobotDriveSolution.robot.drive(0,1)] and RobotDriveSolution.robot.drive(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotDriveSolution.robot.drive(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotdrivesolution_robot_self[dst_runtime]->_lf_drive = (_robot_drive_t*)&robotdrivesolution_main_self[src_runtime]->_lf_robot.drive;
        }
    }
    // Connect RobotDriveSolution.robot.notify(0,1)->[RobotDriveSolution.display.line0(0,1)] to port RobotDriveSolution.display.line0(0,1)
    // Iterate over ranges RobotDriveSolution.robot.notify(0,1)->[RobotDriveSolution.display.line0(0,1)] and RobotDriveSolution.display.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotDriveSolution.display.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotdrivesolution_display_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&robotdrivesolution_robot_self[src_runtime]->_lf_notify;
        }
    }
    // Connect inputs and outputs for reactor RobotDriveSolution.robot.motors.
    // Connect RobotDriveSolution.robot.motors.left_power(0,1)->[RobotDriveSolution.robot.motors.left_power(0,1)] to port RobotDriveSolution.robot.motors.left_power(0,1)
    // Iterate over ranges RobotDriveSolution.robot.motors.left_power(0,1)->[RobotDriveSolution.robot.motors.left_power(0,1)] and RobotDriveSolution.robot.motors.left_power(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotDriveSolution.robot.motors.left_power(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotdrivesolution_robot_motors_self[dst_runtime]->_lf_left_power = (_motors_left_power_t*)&robotdrivesolution_robot_self[src_runtime]->_lf_motors.left_power;
        }
    }
    // Connect RobotDriveSolution.robot.motors.right_power(0,1)->[RobotDriveSolution.robot.motors.right_power(0,1)] to port RobotDriveSolution.robot.motors.right_power(0,1)
    // Iterate over ranges RobotDriveSolution.robot.motors.right_power(0,1)->[RobotDriveSolution.robot.motors.right_power(0,1)] and RobotDriveSolution.robot.motors.right_power(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotDriveSolution.robot.motors.right_power(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotdrivesolution_robot_motors_self[dst_runtime]->_lf_right_power = (_motors_right_power_t*)&robotdrivesolution_robot_self[src_runtime]->_lf_motors.right_power;
        }
    }
    // Connect inputs and outputs for reactor RobotDriveSolution.display.
    {
        {
        }
        // Add port RobotDriveSolution.robot.motors.left_power to array of is_present fields.
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            {
                {
                    envs[robotdrivesolution_main].is_present_fields[0 + count] = &robotdrivesolution_robot_self[0]->_lf_motors.left_power.is_present;
                    #ifdef FEDERATED_DECENTRALIZED
                    envs[robotdrivesolution_main]._lf_intended_tag_fields[0 + count] = &robotdrivesolution_robot_self[0]->_lf_motors.left_power.intended_tag;
                    #endif // FEDERATED_DECENTRALIZED
                    count++;
                }
            }
        }
        // Add port RobotDriveSolution.robot.motors.right_power to array of is_present fields.
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            {
                {
                    envs[robotdrivesolution_main].is_present_fields[1 + count] = &robotdrivesolution_robot_self[0]->_lf_motors.right_power.is_present;
                    #ifdef FEDERATED_DECENTRALIZED
                    envs[robotdrivesolution_main]._lf_intended_tag_fields[1 + count] = &robotdrivesolution_robot_self[0]->_lf_motors.right_power.intended_tag;
                    #endif // FEDERATED_DECENTRALIZED
                    count++;
                }
            }
        }
    }
    {
    }
    // Add port RobotDriveSolution.robot.drive to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[robotdrivesolution_main].is_present_fields[2 + count] = &robotdrivesolution_main_self[0]->_lf_robot.drive.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[robotdrivesolution_main]._lf_intended_tag_fields[2 + count] = &robotdrivesolution_main_self[0]->_lf_robot.drive.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port RobotDriveSolution.robot.notify to array of is_present fields.
            envs[robotdrivesolution_main].is_present_fields[3 + count] = &robotdrivesolution_robot_self[0]->_lf_notify.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port RobotDriveSolution.robot.notify to array of intended_tag fields.
            envs[robotdrivesolution_main]._lf_intended_tag_fields[3 + count] = &robotdrivesolution_robot_self[0]->_lf_notify.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance RobotDriveSolution
    {
        robotdrivesolution_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        robotdrivesolution_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
    
        // Set reaction priorities for ReactorInstance RobotDriveSolution.robot
        {
            robotdrivesolution_robot_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robotdrivesolution_robot_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            robotdrivesolution_robot_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robotdrivesolution_robot_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
            robotdrivesolution_robot_self[0]->_lf__reaction_2.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robotdrivesolution_robot_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
        
            // Set reaction priorities for ReactorInstance RobotDriveSolution.robot.motors
            {
                robotdrivesolution_robot_motors_self[0]->_lf__reaction_0.chain_id = 1;
                // index is the OR of level 0 and 
                // deadline 9223372036854775807 shifted left 16 bits.
                robotdrivesolution_robot_motors_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
                robotdrivesolution_robot_motors_self[0]->_lf__reaction_1.chain_id = 1;
                // index is the OR of level 3 and 
                // deadline 9223372036854775807 shifted left 16 bits.
                robotdrivesolution_robot_motors_self[0]->_lf__reaction_1.index = 0xffffffffffff0003LL;
                robotdrivesolution_robot_motors_self[0]->_lf__reaction_2.chain_id = 1;
                // index is the OR of level 4 and 
                // deadline 9223372036854775807 shifted left 16 bits.
                robotdrivesolution_robot_motors_self[0]->_lf__reaction_2.index = 0xffffffffffff0004LL;
            }
        
        }
    
    
        // Set reaction priorities for ReactorInstance RobotDriveSolution.display
        {
            robotdrivesolution_display_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robotdrivesolution_display_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            robotdrivesolution_display_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robotdrivesolution_display_self[0]->_lf__reaction_1.index = 0xffffffffffff0003LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
