// Code generated by the Lingua Franca compiler from:
// file://home/foobar/EECS149Proj/PololuCharacterization/src/SimpleLineFollow.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/EECS149Proj/PololuCharacterization/src-gen/SimpleLineFollow"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_motors.h"
#include "_robotlinefollower.h"
#include "_irsensorreader.h"
#include "_display.h"
#include "_simplelinefollow_main.h"
typedef enum {
    simplelinefollow_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[simplelinefollow_main],simplelinefollow_main,_lf_number_of_workers,2,4,0,0,9,1,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _simplelinefollow_main_main_self_t* simplelinefollow_main_self[1];
    SUPPRESS_UNUSED_WARNING(simplelinefollow_main_self);
    _robotlinefollower_self_t* simplelinefollow_robot_self[1];
    SUPPRESS_UNUSED_WARNING(simplelinefollow_robot_self);
    _motors_self_t* simplelinefollow_robot_motors_self[1];
    SUPPRESS_UNUSED_WARNING(simplelinefollow_robot_motors_self);
    _irsensorreader_self_t* simplelinefollow_irsensor_self[1];
    SUPPRESS_UNUSED_WARNING(simplelinefollow_irsensor_self);
    _display_self_t* simplelinefollow_display_self[1];
    SUPPRESS_UNUSED_WARNING(simplelinefollow_display_self);
    // ***** Start initializing SimpleLineFollow of class SimpleLineFollow
    simplelinefollow_main_self[0] = new__simplelinefollow_main();
    simplelinefollow_main_self[0]->base.environment = &envs[simplelinefollow_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    { // For scoping
        static bool _initial = true;
        simplelinefollow_main_self[0]->drive = _initial;
    } // End scoping.
    // Initiaizing timer SimpleLineFollow.t.
    simplelinefollow_main_self[0]->_lf__t.offset = 0;
    simplelinefollow_main_self[0]->_lf__t.period = MSEC(50);
    // Associate timer with the environment of its parent
    envs[simplelinefollow_main].timer_triggers[timer_triggers_count[simplelinefollow_main]++] = &simplelinefollow_main_self[0]->_lf__t;
    simplelinefollow_main_self[0]->_lf__t.mode = NULL;
    
    {
        // ***** Start initializing SimpleLineFollow.robot of class RobotLineFollower
        simplelinefollow_robot_self[0] = new__robotlinefollower();
        simplelinefollow_robot_self[0]->base.environment = &envs[simplelinefollow_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_robot_self[0]->_lf_notify1_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_robot_self[0]->_lf_notify2_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_robot_self[0]->_lf_notify3_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_robot_self[0]->_lf_notify4_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_robot_self[0]->_lf_drive_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_robot_self[0]->_lf_IR_1_val_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_robot_self[0]->_lf_IR_LEFT_val_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_robot_self[0]->_lf_IR_RIGHT_val_width = -2;
        envs[simplelinefollow_main].startup_reactions[startup_reaction_count[simplelinefollow_main]++] = &simplelinefollow_robot_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        simplelinefollow_robot_self[0]->_lf__reaction_0.deadline = NEVER;
        simplelinefollow_robot_self[0]->_lf__reaction_1.deadline = NEVER;
        // Register for transition handling
        envs[simplelinefollow_main].modes->modal_reactor_states[modal_reactor_count[simplelinefollow_main]++] = &((self_base_t*)simplelinefollow_robot_self[0])->_lf__mode_state;
        {
            // ***** Start initializing SimpleLineFollow.robot.motors of class Motors
            simplelinefollow_robot_motors_self[0] = new__motors();
            simplelinefollow_robot_motors_self[0]->base.environment = &envs[simplelinefollow_main];
            bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
            // width of -2 indicates that it is not a multiport.
            simplelinefollow_robot_motors_self[0]->_lf_left_power_width = -2;
            // width of -2 indicates that it is not a multiport.
            simplelinefollow_robot_motors_self[0]->_lf_right_power_width = -2;
            envs[simplelinefollow_main].startup_reactions[startup_reaction_count[simplelinefollow_main]++] = &simplelinefollow_robot_motors_self[0]->_lf__reaction_0;
            SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
            simplelinefollow_robot_motors_self[0]->_lf__reaction_0.deadline = NEVER;
            simplelinefollow_robot_motors_self[0]->_lf__reaction_1.deadline = NEVER;
            simplelinefollow_robot_motors_self[0]->_lf__reaction_2.deadline = NEVER;
            //***** End initializing SimpleLineFollow.robot.motors
        }
        //***** End initializing SimpleLineFollow.robot
    }
    {
        // ***** Start initializing SimpleLineFollow.IRSensor of class IRSensorReader
        simplelinefollow_irsensor_self[0] = new__irsensorreader();
        simplelinefollow_irsensor_self[0]->base.environment = &envs[simplelinefollow_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_irsensor_self[0]->_lf_IR_1_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_irsensor_self[0]->_lf_IR_LEFT_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_irsensor_self[0]->_lf_IR_RIGHT_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_irsensor_self[0]->_lf_notify1_width = -2;
        envs[simplelinefollow_main].startup_reactions[startup_reaction_count[simplelinefollow_main]++] = &simplelinefollow_irsensor_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        // Initiaizing timer SimpleLineFollow.IRSensor.sampleIRs.
        simplelinefollow_irsensor_self[0]->_lf__sampleIRs.offset = 0;
        simplelinefollow_irsensor_self[0]->_lf__sampleIRs.period = MSEC(10);
        // Associate timer with the environment of its parent
        envs[simplelinefollow_main].timer_triggers[timer_triggers_count[simplelinefollow_main]++] = &simplelinefollow_irsensor_self[0]->_lf__sampleIRs;
        simplelinefollow_irsensor_self[0]->_lf__sampleIRs.mode = NULL;
    
        simplelinefollow_irsensor_self[0]->_lf__reaction_0.deadline = NEVER;
        simplelinefollow_irsensor_self[0]->_lf__reaction_1.deadline = NEVER;
        simplelinefollow_irsensor_self[0]->_lf__reaction_2.deadline = NEVER;
        simplelinefollow_irsensor_self[0]->_lf__reaction_3.deadline = NEVER;
        //***** End initializing SimpleLineFollow.IRSensor
    }
    {
        // ***** Start initializing SimpleLineFollow.display of class Display
        simplelinefollow_display_self[0] = new__display();
        simplelinefollow_display_self[0]->base.environment = &envs[simplelinefollow_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_display_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_display_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_display_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        simplelinefollow_display_self[0]->_lf_line3_width = -2;
        envs[simplelinefollow_main].startup_reactions[startup_reaction_count[simplelinefollow_main]++] = &simplelinefollow_display_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        simplelinefollow_display_self[0]->_lf__reaction_0.deadline = NEVER;
        simplelinefollow_display_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing SimpleLineFollow.display
    }
    //***** End initializing SimpleLineFollow
    // **** Start deferred initialize for SimpleLineFollow
    {
    
    
    
        // **** Start deferred initialize for SimpleLineFollow.robot
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of SimpleLineFollow.robot.
            simplelinefollow_robot_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            simplelinefollow_robot_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &simplelinefollow_robot_self[0]->base.allocations);
            simplelinefollow_robot_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &simplelinefollow_robot_self[0]->base.allocations);
            simplelinefollow_robot_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &simplelinefollow_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    simplelinefollow_robot_self[0]->_lf__reaction_0.output_produced[count++] = &simplelinefollow_robot_self[0]->_lf_notify1.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of SimpleLineFollow.robot
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of SimpleLineFollow.robot.
            simplelinefollow_robot_self[0]->_lf__reaction_1.num_outputs = 6;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            simplelinefollow_robot_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    6, sizeof(trigger_t**),
                    &simplelinefollow_robot_self[0]->base.allocations);
            simplelinefollow_robot_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    6, sizeof(int),
                    &simplelinefollow_robot_self[0]->base.allocations);
            simplelinefollow_robot_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    6, sizeof(bool*),
                    &simplelinefollow_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    simplelinefollow_robot_self[0]->_lf__reaction_1.output_produced[count++] = &simplelinefollow_robot_self[0]->_lf_notify1.is_present;
                }
                {
                    simplelinefollow_robot_self[0]->_lf__reaction_1.output_produced[count++] = &simplelinefollow_robot_self[0]->_lf_notify2.is_present;
                }
                {
                    simplelinefollow_robot_self[0]->_lf__reaction_1.output_produced[count++] = &simplelinefollow_robot_self[0]->_lf_notify3.is_present;
                }
                {
                    simplelinefollow_robot_self[0]->_lf__reaction_1.output_produced[count++] = &simplelinefollow_robot_self[0]->_lf_notify4.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    simplelinefollow_robot_self[0]->_lf__reaction_1.output_produced[count++] = &simplelinefollow_robot_self[0]->_lf_motors.left_power.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    simplelinefollow_robot_self[0]->_lf__reaction_1.output_produced[count++] = &simplelinefollow_robot_self[0]->_lf_motors.right_power.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of SimpleLineFollow.robot
        
            // **** Start deferred initialize for SimpleLineFollow.robot.motors
            {
            
                // Total number of outputs (single ports and multiport channels)
                // produced by reaction_0 of SimpleLineFollow.robot.motors.
                simplelinefollow_robot_motors_self[0]->_lf__reaction_0.num_outputs = 0;
                {
                    int count = 0; SUPPRESS_UNUSED_WARNING(count);
                }
                
                // ** End initialization for reaction 0 of SimpleLineFollow.robot.motors
                // Total number of outputs (single ports and multiport channels)
                // produced by reaction_1 of SimpleLineFollow.robot.motors.
                simplelinefollow_robot_motors_self[0]->_lf__reaction_1.num_outputs = 0;
                {
                    int count = 0; SUPPRESS_UNUSED_WARNING(count);
                }
                
                // ** End initialization for reaction 1 of SimpleLineFollow.robot.motors
                // Total number of outputs (single ports and multiport channels)
                // produced by reaction_2 of SimpleLineFollow.robot.motors.
                simplelinefollow_robot_motors_self[0]->_lf__reaction_2.num_outputs = 0;
                {
                    int count = 0; SUPPRESS_UNUSED_WARNING(count);
                }
                
                // ** End initialization for reaction 2 of SimpleLineFollow.robot.motors
            
            }
            // **** End of deferred initialize for SimpleLineFollow.robot.motors
        }
        // **** End of deferred initialize for SimpleLineFollow.robot
        // **** Start deferred initialize for SimpleLineFollow.IRSensor
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of SimpleLineFollow.IRSensor.
            simplelinefollow_irsensor_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of SimpleLineFollow.IRSensor
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of SimpleLineFollow.IRSensor.
            simplelinefollow_irsensor_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            simplelinefollow_irsensor_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &simplelinefollow_irsensor_self[0]->base.allocations);
            simplelinefollow_irsensor_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &simplelinefollow_irsensor_self[0]->base.allocations);
            simplelinefollow_irsensor_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &simplelinefollow_irsensor_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    simplelinefollow_irsensor_self[0]->_lf__reaction_1.output_produced[count++] = &simplelinefollow_irsensor_self[0]->_lf_IR_1_out.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of SimpleLineFollow.IRSensor
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of SimpleLineFollow.IRSensor.
            simplelinefollow_irsensor_self[0]->_lf__reaction_2.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            simplelinefollow_irsensor_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &simplelinefollow_irsensor_self[0]->base.allocations);
            simplelinefollow_irsensor_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &simplelinefollow_irsensor_self[0]->base.allocations);
            simplelinefollow_irsensor_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &simplelinefollow_irsensor_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    simplelinefollow_irsensor_self[0]->_lf__reaction_2.output_produced[count++] = &simplelinefollow_irsensor_self[0]->_lf_IR_LEFT_out.is_present;
                }
            }
            
            // ** End initialization for reaction 2 of SimpleLineFollow.IRSensor
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of SimpleLineFollow.IRSensor.
            simplelinefollow_irsensor_self[0]->_lf__reaction_3.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            simplelinefollow_irsensor_self[0]->_lf__reaction_3.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &simplelinefollow_irsensor_self[0]->base.allocations);
            simplelinefollow_irsensor_self[0]->_lf__reaction_3.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &simplelinefollow_irsensor_self[0]->base.allocations);
            simplelinefollow_irsensor_self[0]->_lf__reaction_3.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &simplelinefollow_irsensor_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    simplelinefollow_irsensor_self[0]->_lf__reaction_3.output_produced[count++] = &simplelinefollow_irsensor_self[0]->_lf_IR_RIGHT_out.is_present;
                }
            }
            
            // ** End initialization for reaction 3 of SimpleLineFollow.IRSensor
        
        }
        // **** End of deferred initialize for SimpleLineFollow.IRSensor
        // **** Start deferred initialize for SimpleLineFollow.display
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of SimpleLineFollow.display.
            simplelinefollow_display_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of SimpleLineFollow.display
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of SimpleLineFollow.display.
            simplelinefollow_display_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of SimpleLineFollow.display
        
        }
        // **** End of deferred initialize for SimpleLineFollow.display
    }
    // **** End of deferred initialize for SimpleLineFollow
    // **** Start non-nested deferred initialize for SimpleLineFollow
    
    
    
    // **** Start non-nested deferred initialize for SimpleLineFollow.robot
    // Set number of destination reactors for port motors.left_power.
    // Iterate over range SimpleLineFollow.robot.motors.left_power(0,1)->[SimpleLineFollow.robot.motors.left_power(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        simplelinefollow_robot_self[src_runtime]->_lf_motors.left_power._base.num_destinations = 1;
        simplelinefollow_robot_self[src_runtime]->_lf_motors.left_power._base.source_reactor = (self_base_t*)simplelinefollow_robot_self[src_runtime];
    }
    // Set number of destination reactors for port motors.right_power.
    // Iterate over range SimpleLineFollow.robot.motors.right_power(0,1)->[SimpleLineFollow.robot.motors.right_power(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        simplelinefollow_robot_self[src_runtime]->_lf_motors.right_power._base.num_destinations = 1;
        simplelinefollow_robot_self[src_runtime]->_lf_motors.right_power._base.source_reactor = (self_base_t*)simplelinefollow_robot_self[src_runtime];
    }
    // For reference counting, set num_destinations for port SimpleLineFollow.robot.notify1.
    // Iterate over range SimpleLineFollow.robot.notify1(0,1)->[SimpleLineFollow.display.line0(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        simplelinefollow_robot_self[src_runtime]->_lf_notify1._base.num_destinations = 1;
        simplelinefollow_robot_self[src_runtime]->_lf_notify1._base.source_reactor = (self_base_t*)simplelinefollow_robot_self[src_runtime];
    }
    // For reference counting, set num_destinations for port SimpleLineFollow.robot.notify2.
    // Iterate over range SimpleLineFollow.robot.notify2(0,1)->[SimpleLineFollow.display.line1(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        simplelinefollow_robot_self[src_runtime]->_lf_notify2._base.num_destinations = 1;
        simplelinefollow_robot_self[src_runtime]->_lf_notify2._base.source_reactor = (self_base_t*)simplelinefollow_robot_self[src_runtime];
    }
    // For reference counting, set num_destinations for port SimpleLineFollow.robot.notify3.
    // Iterate over range SimpleLineFollow.robot.notify3(0,1)->[SimpleLineFollow.display.line2(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        simplelinefollow_robot_self[src_runtime]->_lf_notify3._base.num_destinations = 1;
        simplelinefollow_robot_self[src_runtime]->_lf_notify3._base.source_reactor = (self_base_t*)simplelinefollow_robot_self[src_runtime];
    }
    // For reference counting, set num_destinations for port SimpleLineFollow.robot.notify4.
    // Iterate over range SimpleLineFollow.robot.notify4(0,1)->[SimpleLineFollow.display.line3(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        simplelinefollow_robot_self[src_runtime]->_lf_notify4._base.num_destinations = 1;
        simplelinefollow_robot_self[src_runtime]->_lf_notify4._base.source_reactor = (self_base_t*)simplelinefollow_robot_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range SimpleLineFollow.robot.notify1(0,1)->[SimpleLineFollow.display.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of SimpleLineFollow.robot triggers 1 downstream reactions
            // through port SimpleLineFollow.robot.notify1.
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of SimpleLineFollow.robot, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.robot.notify1
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_robot_self[src_runtime]->base.allocations); 
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges SimpleLineFollow.robot.notify1(0,1)->[SimpleLineFollow.display.line0(0,1)] and SimpleLineFollow.display.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.display.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.display.line0's trigger struct.
                simplelinefollow_robot_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_display_self[dst_runtime]->_lf__line0;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range SimpleLineFollow.robot.notify1(0,1)->[SimpleLineFollow.display.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of SimpleLineFollow.robot triggers 1 downstream reactions
            // through port SimpleLineFollow.robot.notify1.
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of SimpleLineFollow.robot, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.robot.notify1
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_robot_self[src_runtime]->base.allocations); 
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range SimpleLineFollow.robot.notify2(0,1)->[SimpleLineFollow.display.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of SimpleLineFollow.robot triggers 1 downstream reactions
            // through port SimpleLineFollow.robot.notify2.
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of SimpleLineFollow.robot, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.robot.notify2
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_robot_self[src_runtime]->base.allocations); 
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range SimpleLineFollow.robot.notify3(0,1)->[SimpleLineFollow.display.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of SimpleLineFollow.robot triggers 1 downstream reactions
            // through port SimpleLineFollow.robot.notify3.
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of SimpleLineFollow.robot, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.robot.notify3
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_robot_self[src_runtime]->base.allocations); 
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range SimpleLineFollow.robot.notify4(0,1)->[SimpleLineFollow.display.line3(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of SimpleLineFollow.robot triggers 1 downstream reactions
            // through port SimpleLineFollow.robot.notify4.
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of SimpleLineFollow.robot, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.robot.notify4
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_robot_self[src_runtime]->base.allocations); 
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range SimpleLineFollow.robot.motors.left_power(0,1)->[SimpleLineFollow.robot.motors.left_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of SimpleLineFollow.robot triggers 1 downstream reactions
            // through port SimpleLineFollow.robot.motors.left_power.
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of SimpleLineFollow.robot, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.robot.motors.left_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_robot_self[src_runtime]->base.allocations); 
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range SimpleLineFollow.robot.motors.right_power(0,1)->[SimpleLineFollow.robot.motors.right_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of SimpleLineFollow.robot triggers 1 downstream reactions
            // through port SimpleLineFollow.robot.motors.right_power.
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of SimpleLineFollow.robot, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.robot.motors.right_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_robot_self[src_runtime]->base.allocations); 
            simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges SimpleLineFollow.robot.notify1(0,1)->[SimpleLineFollow.display.line0(0,1)] and SimpleLineFollow.display.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.display.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.display.line0's trigger struct.
                simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_display_self[dst_runtime]->_lf__line0;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges SimpleLineFollow.robot.notify2(0,1)->[SimpleLineFollow.display.line1(0,1)] and SimpleLineFollow.display.line1(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.display.line1(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.display.line1's trigger struct.
                simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_display_self[dst_runtime]->_lf__line1;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges SimpleLineFollow.robot.notify3(0,1)->[SimpleLineFollow.display.line2(0,1)] and SimpleLineFollow.display.line2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.display.line2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.display.line2's trigger struct.
                simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_display_self[dst_runtime]->_lf__line2;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 3;
        // Iterate over ranges SimpleLineFollow.robot.notify4(0,1)->[SimpleLineFollow.display.line3(0,1)] and SimpleLineFollow.display.line3(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.display.line3(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.display.line3's trigger struct.
                simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_display_self[dst_runtime]->_lf__line3;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 4;
        // Iterate over ranges SimpleLineFollow.robot.motors.left_power(0,1)->[SimpleLineFollow.robot.motors.left_power(0,1)] and SimpleLineFollow.robot.motors.left_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.robot.motors.left_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.robot.motors.left_power's trigger struct.
                simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_robot_motors_self[dst_runtime]->_lf__left_power;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 5;
        // Iterate over ranges SimpleLineFollow.robot.motors.right_power(0,1)->[SimpleLineFollow.robot.motors.right_power(0,1)] and SimpleLineFollow.robot.motors.right_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.robot.motors.right_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.robot.motors.right_power's trigger struct.
                simplelinefollow_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_robot_motors_self[dst_runtime]->_lf__right_power;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for SimpleLineFollow.robot.motors
    
    
    
    
    // **** End of non-nested deferred initialize for SimpleLineFollow.robot.motors
    // **** End of non-nested deferred initialize for SimpleLineFollow.robot
    // **** Start non-nested deferred initialize for SimpleLineFollow.IRSensor
    
    // For reference counting, set num_destinations for port SimpleLineFollow.IRSensor.IR_1_out.
    // Iterate over range SimpleLineFollow.IRSensor.IR_1_out(0,1)->[SimpleLineFollow.robot.IR_1_val(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        simplelinefollow_irsensor_self[src_runtime]->_lf_IR_1_out._base.num_destinations = 1;
        simplelinefollow_irsensor_self[src_runtime]->_lf_IR_1_out._base.source_reactor = (self_base_t*)simplelinefollow_irsensor_self[src_runtime];
    }
    // For reference counting, set num_destinations for port SimpleLineFollow.IRSensor.IR_LEFT_out.
    // Iterate over range SimpleLineFollow.IRSensor.IR_LEFT_out(0,1)->[SimpleLineFollow.robot.IR_LEFT_val(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        simplelinefollow_irsensor_self[src_runtime]->_lf_IR_LEFT_out._base.num_destinations = 1;
        simplelinefollow_irsensor_self[src_runtime]->_lf_IR_LEFT_out._base.source_reactor = (self_base_t*)simplelinefollow_irsensor_self[src_runtime];
    }
    // For reference counting, set num_destinations for port SimpleLineFollow.IRSensor.IR_RIGHT_out.
    // Iterate over range SimpleLineFollow.IRSensor.IR_RIGHT_out(0,1)->[SimpleLineFollow.robot.IR_RIGHT_val(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        simplelinefollow_irsensor_self[src_runtime]->_lf_IR_RIGHT_out._base.num_destinations = 1;
        simplelinefollow_irsensor_self[src_runtime]->_lf_IR_RIGHT_out._base.source_reactor = (self_base_t*)simplelinefollow_irsensor_self[src_runtime];
    }
    simplelinefollow_irsensor_self[0]->_lf_notify1._base.source_reactor = (self_base_t*)simplelinefollow_irsensor_self[0];
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range SimpleLineFollow.IRSensor.IR_1_out(0,1)->[SimpleLineFollow.robot.IR_1_val(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of SimpleLineFollow.IRSensor triggers 1 downstream reactions
            // through port SimpleLineFollow.IRSensor.IR_1_out.
            simplelinefollow_irsensor_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of SimpleLineFollow.IRSensor, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.IRSensor.IR_1_out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_irsensor_self[src_runtime]->base.allocations); 
            simplelinefollow_irsensor_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges SimpleLineFollow.IRSensor.IR_1_out(0,1)->[SimpleLineFollow.robot.IR_1_val(0,1)] and SimpleLineFollow.robot.IR_1_val(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.robot.IR_1_val(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.robot.IR_1_val's trigger struct.
                simplelinefollow_irsensor_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_robot_self[dst_runtime]->_lf__IR_1_val;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range SimpleLineFollow.IRSensor.IR_LEFT_out(0,1)->[SimpleLineFollow.robot.IR_LEFT_val(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of SimpleLineFollow.IRSensor triggers 1 downstream reactions
            // through port SimpleLineFollow.IRSensor.IR_LEFT_out.
            simplelinefollow_irsensor_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of SimpleLineFollow.IRSensor, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.IRSensor.IR_LEFT_out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_irsensor_self[src_runtime]->base.allocations); 
            simplelinefollow_irsensor_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges SimpleLineFollow.IRSensor.IR_LEFT_out(0,1)->[SimpleLineFollow.robot.IR_LEFT_val(0,1)] and SimpleLineFollow.robot.IR_LEFT_val(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.robot.IR_LEFT_val(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.robot.IR_LEFT_val's trigger struct.
                simplelinefollow_irsensor_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_robot_self[dst_runtime]->_lf__IR_LEFT_val;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range SimpleLineFollow.IRSensor.IR_RIGHT_out(0,1)->[SimpleLineFollow.robot.IR_RIGHT_val(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 3 of SimpleLineFollow.IRSensor triggers 1 downstream reactions
            // through port SimpleLineFollow.IRSensor.IR_RIGHT_out.
            simplelinefollow_irsensor_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 3 of SimpleLineFollow.IRSensor, allocate an
            // array of trigger pointers for downstream reactions through port SimpleLineFollow.IRSensor.IR_RIGHT_out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &simplelinefollow_irsensor_self[src_runtime]->base.allocations); 
            simplelinefollow_irsensor_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges SimpleLineFollow.IRSensor.IR_RIGHT_out(0,1)->[SimpleLineFollow.robot.IR_RIGHT_val(0,1)] and SimpleLineFollow.robot.IR_RIGHT_val(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range SimpleLineFollow.robot.IR_RIGHT_val(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port SimpleLineFollow.robot.IR_RIGHT_val's trigger struct.
                simplelinefollow_irsensor_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &simplelinefollow_robot_self[dst_runtime]->_lf__IR_RIGHT_val;
            }
        }
    }
    
    // **** End of non-nested deferred initialize for SimpleLineFollow.IRSensor
    // **** Start non-nested deferred initialize for SimpleLineFollow.display
    
    
    
    
    // **** End of non-nested deferred initialize for SimpleLineFollow.display
    // **** End of non-nested deferred initialize for SimpleLineFollow
    // Connect inputs and outputs for reactor SimpleLineFollow.
    // Connect inputs and outputs for reactor SimpleLineFollow.robot.
    // Connect SimpleLineFollow.robot.notify1(0,1)->[SimpleLineFollow.display.line0(0,1)] to port SimpleLineFollow.display.line0(0,1)
    // Iterate over ranges SimpleLineFollow.robot.notify1(0,1)->[SimpleLineFollow.display.line0(0,1)] and SimpleLineFollow.display.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range SimpleLineFollow.display.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            simplelinefollow_display_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&simplelinefollow_robot_self[src_runtime]->_lf_notify1;
        }
    }
    // Connect SimpleLineFollow.robot.notify2(0,1)->[SimpleLineFollow.display.line1(0,1)] to port SimpleLineFollow.display.line1(0,1)
    // Iterate over ranges SimpleLineFollow.robot.notify2(0,1)->[SimpleLineFollow.display.line1(0,1)] and SimpleLineFollow.display.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range SimpleLineFollow.display.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            simplelinefollow_display_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&simplelinefollow_robot_self[src_runtime]->_lf_notify2;
        }
    }
    // Connect SimpleLineFollow.robot.notify3(0,1)->[SimpleLineFollow.display.line2(0,1)] to port SimpleLineFollow.display.line2(0,1)
    // Iterate over ranges SimpleLineFollow.robot.notify3(0,1)->[SimpleLineFollow.display.line2(0,1)] and SimpleLineFollow.display.line2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range SimpleLineFollow.display.line2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            simplelinefollow_display_self[dst_runtime]->_lf_line2 = (_display_line2_t*)&simplelinefollow_robot_self[src_runtime]->_lf_notify3;
        }
    }
    // Connect SimpleLineFollow.robot.notify4(0,1)->[SimpleLineFollow.display.line3(0,1)] to port SimpleLineFollow.display.line3(0,1)
    // Iterate over ranges SimpleLineFollow.robot.notify4(0,1)->[SimpleLineFollow.display.line3(0,1)] and SimpleLineFollow.display.line3(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range SimpleLineFollow.display.line3(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            simplelinefollow_display_self[dst_runtime]->_lf_line3 = (_display_line3_t*)&simplelinefollow_robot_self[src_runtime]->_lf_notify4;
        }
    }
    // Connect inputs and outputs for reactor SimpleLineFollow.robot.motors.
    // Connect SimpleLineFollow.robot.motors.left_power(0,1)->[SimpleLineFollow.robot.motors.left_power(0,1)] to port SimpleLineFollow.robot.motors.left_power(0,1)
    // Iterate over ranges SimpleLineFollow.robot.motors.left_power(0,1)->[SimpleLineFollow.robot.motors.left_power(0,1)] and SimpleLineFollow.robot.motors.left_power(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range SimpleLineFollow.robot.motors.left_power(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            simplelinefollow_robot_motors_self[dst_runtime]->_lf_left_power = (_motors_left_power_t*)&simplelinefollow_robot_self[src_runtime]->_lf_motors.left_power;
        }
    }
    // Connect SimpleLineFollow.robot.motors.right_power(0,1)->[SimpleLineFollow.robot.motors.right_power(0,1)] to port SimpleLineFollow.robot.motors.right_power(0,1)
    // Iterate over ranges SimpleLineFollow.robot.motors.right_power(0,1)->[SimpleLineFollow.robot.motors.right_power(0,1)] and SimpleLineFollow.robot.motors.right_power(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range SimpleLineFollow.robot.motors.right_power(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            simplelinefollow_robot_motors_self[dst_runtime]->_lf_right_power = (_motors_right_power_t*)&simplelinefollow_robot_self[src_runtime]->_lf_motors.right_power;
        }
    }
    // Connect inputs and outputs for reactor SimpleLineFollow.IRSensor.
    // Connect SimpleLineFollow.IRSensor.IR_1_out(0,1)->[SimpleLineFollow.robot.IR_1_val(0,1)] to port SimpleLineFollow.robot.IR_1_val(0,1)
    // Iterate over ranges SimpleLineFollow.IRSensor.IR_1_out(0,1)->[SimpleLineFollow.robot.IR_1_val(0,1)] and SimpleLineFollow.robot.IR_1_val(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range SimpleLineFollow.robot.IR_1_val(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            simplelinefollow_robot_self[dst_runtime]->_lf_IR_1_val = (_robotlinefollower_IR_1_val_t*)&simplelinefollow_irsensor_self[src_runtime]->_lf_IR_1_out;
        }
    }
    // Connect SimpleLineFollow.IRSensor.IR_LEFT_out(0,1)->[SimpleLineFollow.robot.IR_LEFT_val(0,1)] to port SimpleLineFollow.robot.IR_LEFT_val(0,1)
    // Iterate over ranges SimpleLineFollow.IRSensor.IR_LEFT_out(0,1)->[SimpleLineFollow.robot.IR_LEFT_val(0,1)] and SimpleLineFollow.robot.IR_LEFT_val(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range SimpleLineFollow.robot.IR_LEFT_val(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            simplelinefollow_robot_self[dst_runtime]->_lf_IR_LEFT_val = (_robotlinefollower_IR_LEFT_val_t*)&simplelinefollow_irsensor_self[src_runtime]->_lf_IR_LEFT_out;
        }
    }
    // Connect SimpleLineFollow.IRSensor.IR_RIGHT_out(0,1)->[SimpleLineFollow.robot.IR_RIGHT_val(0,1)] to port SimpleLineFollow.robot.IR_RIGHT_val(0,1)
    // Iterate over ranges SimpleLineFollow.IRSensor.IR_RIGHT_out(0,1)->[SimpleLineFollow.robot.IR_RIGHT_val(0,1)] and SimpleLineFollow.robot.IR_RIGHT_val(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range SimpleLineFollow.robot.IR_RIGHT_val(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            simplelinefollow_robot_self[dst_runtime]->_lf_IR_RIGHT_val = (_robotlinefollower_IR_RIGHT_val_t*)&simplelinefollow_irsensor_self[src_runtime]->_lf_IR_RIGHT_out;
        }
    }
    // Connect inputs and outputs for reactor SimpleLineFollow.display.
    {
        {
        }
        // Add port SimpleLineFollow.robot.motors.left_power to array of is_present fields.
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            {
                {
                    envs[simplelinefollow_main].is_present_fields[0 + count] = &simplelinefollow_robot_self[0]->_lf_motors.left_power.is_present;
                    #ifdef FEDERATED_DECENTRALIZED
                    envs[simplelinefollow_main]._lf_intended_tag_fields[0 + count] = &simplelinefollow_robot_self[0]->_lf_motors.left_power.intended_tag;
                    #endif // FEDERATED_DECENTRALIZED
                    count++;
                }
            }
        }
        // Add port SimpleLineFollow.robot.motors.right_power to array of is_present fields.
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            {
                {
                    envs[simplelinefollow_main].is_present_fields[1 + count] = &simplelinefollow_robot_self[0]->_lf_motors.right_power.is_present;
                    #ifdef FEDERATED_DECENTRALIZED
                    envs[simplelinefollow_main]._lf_intended_tag_fields[1 + count] = &simplelinefollow_robot_self[0]->_lf_motors.right_power.intended_tag;
                    #endif // FEDERATED_DECENTRALIZED
                    count++;
                }
            }
        }
    }
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port SimpleLineFollow.robot.notify1 to array of is_present fields.
            envs[simplelinefollow_main].is_present_fields[2 + count] = &simplelinefollow_robot_self[0]->_lf_notify1.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port SimpleLineFollow.robot.notify1 to array of intended_tag fields.
            envs[simplelinefollow_main]._lf_intended_tag_fields[2 + count] = &simplelinefollow_robot_self[0]->_lf_notify1.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port SimpleLineFollow.robot.notify2 to array of is_present fields.
            envs[simplelinefollow_main].is_present_fields[2 + count] = &simplelinefollow_robot_self[0]->_lf_notify2.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port SimpleLineFollow.robot.notify2 to array of intended_tag fields.
            envs[simplelinefollow_main]._lf_intended_tag_fields[2 + count] = &simplelinefollow_robot_self[0]->_lf_notify2.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port SimpleLineFollow.robot.notify3 to array of is_present fields.
            envs[simplelinefollow_main].is_present_fields[2 + count] = &simplelinefollow_robot_self[0]->_lf_notify3.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port SimpleLineFollow.robot.notify3 to array of intended_tag fields.
            envs[simplelinefollow_main]._lf_intended_tag_fields[2 + count] = &simplelinefollow_robot_self[0]->_lf_notify3.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port SimpleLineFollow.robot.notify4 to array of is_present fields.
            envs[simplelinefollow_main].is_present_fields[2 + count] = &simplelinefollow_robot_self[0]->_lf_notify4.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port SimpleLineFollow.robot.notify4 to array of intended_tag fields.
            envs[simplelinefollow_main]._lf_intended_tag_fields[2 + count] = &simplelinefollow_robot_self[0]->_lf_notify4.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port SimpleLineFollow.IRSensor.IR_1_out to array of is_present fields.
            envs[simplelinefollow_main].is_present_fields[6 + count] = &simplelinefollow_irsensor_self[0]->_lf_IR_1_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port SimpleLineFollow.IRSensor.IR_1_out to array of intended_tag fields.
            envs[simplelinefollow_main]._lf_intended_tag_fields[6 + count] = &simplelinefollow_irsensor_self[0]->_lf_IR_1_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port SimpleLineFollow.IRSensor.IR_LEFT_out to array of is_present fields.
            envs[simplelinefollow_main].is_present_fields[6 + count] = &simplelinefollow_irsensor_self[0]->_lf_IR_LEFT_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port SimpleLineFollow.IRSensor.IR_LEFT_out to array of intended_tag fields.
            envs[simplelinefollow_main]._lf_intended_tag_fields[6 + count] = &simplelinefollow_irsensor_self[0]->_lf_IR_LEFT_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port SimpleLineFollow.IRSensor.IR_RIGHT_out to array of is_present fields.
            envs[simplelinefollow_main].is_present_fields[6 + count] = &simplelinefollow_irsensor_self[0]->_lf_IR_RIGHT_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port SimpleLineFollow.IRSensor.IR_RIGHT_out to array of intended_tag fields.
            envs[simplelinefollow_main]._lf_intended_tag_fields[6 + count] = &simplelinefollow_irsensor_self[0]->_lf_IR_RIGHT_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance SimpleLineFollow
    {
    
        // Set reaction priorities for ReactorInstance SimpleLineFollow.robot
        {
            simplelinefollow_robot_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            simplelinefollow_robot_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            simplelinefollow_robot_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            simplelinefollow_robot_self[0]->_lf__reaction_1.index = 0xffffffffffff0004LL;
        
            // Set reaction priorities for ReactorInstance SimpleLineFollow.robot.motors
            {
                simplelinefollow_robot_motors_self[0]->_lf__reaction_0.chain_id = 1;
                // index is the OR of level 0 and 
                // deadline 9223372036854775807 shifted left 16 bits.
                simplelinefollow_robot_motors_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
                simplelinefollow_robot_motors_self[0]->_lf__reaction_1.chain_id = 1;
                // index is the OR of level 5 and 
                // deadline 9223372036854775807 shifted left 16 bits.
                simplelinefollow_robot_motors_self[0]->_lf__reaction_1.index = 0xffffffffffff0005LL;
                simplelinefollow_robot_motors_self[0]->_lf__reaction_2.chain_id = 1;
                // index is the OR of level 6 and 
                // deadline 9223372036854775807 shifted left 16 bits.
                simplelinefollow_robot_motors_self[0]->_lf__reaction_2.index = 0xffffffffffff0006LL;
            }
        
        }
    
    
        // Set reaction priorities for ReactorInstance SimpleLineFollow.IRSensor
        {
            simplelinefollow_irsensor_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            simplelinefollow_irsensor_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            simplelinefollow_irsensor_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            simplelinefollow_irsensor_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
            simplelinefollow_irsensor_self[0]->_lf__reaction_2.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            simplelinefollow_irsensor_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
            simplelinefollow_irsensor_self[0]->_lf__reaction_3.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            simplelinefollow_irsensor_self[0]->_lf__reaction_3.index = 0xffffffffffff0003LL;
        }
    
    
        // Set reaction priorities for ReactorInstance SimpleLineFollow.display
        {
            simplelinefollow_display_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            simplelinefollow_display_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            simplelinefollow_display_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 5 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            simplelinefollow_display_self[0]->_lf__reaction_1.index = 0xffffffffffff0005LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
