// Code generated by the Lingua Franca compiler from:
// file://home/foobar/EECS149Proj/PololuCharacterization/src/ESPDrive.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/EECS149Proj/PololuCharacterization/src-gen/ESPDrive"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_uartrec.h"
#include "_display.h"
#include "_motors.h"
#include "_robot.h"
#include "_espdrive_main.h"
typedef enum {
    espdrive_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[espdrive_main],espdrive_main,_lf_number_of_workers,1,5,0,0,6,2,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _espdrive_main_main_self_t* espdrive_main_self[1];
    SUPPRESS_UNUSED_WARNING(espdrive_main_self);
    _uartrec_self_t* espdrive_uart_self[1];
    SUPPRESS_UNUSED_WARNING(espdrive_uart_self);
    _display_self_t* espdrive_d_self[1];
    SUPPRESS_UNUSED_WARNING(espdrive_d_self);
    _robot_self_t* espdrive_rob_self[1];
    SUPPRESS_UNUSED_WARNING(espdrive_rob_self);
    _motors_self_t* espdrive_rob_motors_self[1];
    SUPPRESS_UNUSED_WARNING(espdrive_rob_motors_self);
    // ***** Start initializing ESPDrive of class ESPDrive
    espdrive_main_self[0] = new__espdrive_main();
    espdrive_main_self[0]->base.environment = &envs[espdrive_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    envs[espdrive_main].startup_reactions[startup_reaction_count[espdrive_main]++] = &espdrive_main_self[0]->_lf__reaction_0;
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    { // For scoping
        static bool _initial = false;
        espdrive_main_self[0]->received = _initial;
    } // End scoping.
    // Initiaizing timer ESPDrive.t.
    espdrive_main_self[0]->_lf__t.offset = 0;
    espdrive_main_self[0]->_lf__t.period = MSEC(1000);
    // Associate timer with the environment of its parent
    envs[espdrive_main].timer_triggers[timer_triggers_count[espdrive_main]++] = &espdrive_main_self[0]->_lf__t;
    espdrive_main_self[0]->_lf__t.mode = NULL;
    
    espdrive_main_self[0]->_lf__reaction_0.deadline = NEVER;
    espdrive_main_self[0]->_lf__reaction_1.deadline = NEVER;
    {
        // ***** Start initializing ESPDrive.uart of class UARTrec
        espdrive_uart_self[0] = new__uartrec();
        espdrive_uart_self[0]->base.environment = &envs[espdrive_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        espdrive_uart_self[0]->_lf_mess_width = -2;
        // width of -2 indicates that it is not a multiport.
        espdrive_uart_self[0]->_lf_rec_width = -2;
        envs[espdrive_main].startup_reactions[startup_reaction_count[espdrive_main]++] = &espdrive_uart_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        espdrive_uart_self[0]->_lf__reaction_0.deadline = NEVER;
        espdrive_uart_self[0]->_lf__reaction_1.deadline = NEVER;
        // Register for transition handling
        envs[espdrive_main].modes->modal_reactor_states[modal_reactor_count[espdrive_main]++] = &((self_base_t*)espdrive_uart_self[0])->_lf__mode_state;
        //***** End initializing ESPDrive.uart
    }
    {
        // ***** Start initializing ESPDrive.d of class Display
        espdrive_d_self[0] = new__display();
        espdrive_d_self[0]->base.environment = &envs[espdrive_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        espdrive_d_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        espdrive_d_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        espdrive_d_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        espdrive_d_self[0]->_lf_line3_width = -2;
        envs[espdrive_main].startup_reactions[startup_reaction_count[espdrive_main]++] = &espdrive_d_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        espdrive_d_self[0]->_lf__reaction_0.deadline = NEVER;
        espdrive_d_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing ESPDrive.d
    }
    {
        // ***** Start initializing ESPDrive.rob of class Robot
        espdrive_rob_self[0] = new__robot();
        espdrive_rob_self[0]->base.environment = &envs[espdrive_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        espdrive_rob_self[0]->_lf_notify_width = -2;
        // width of -2 indicates that it is not a multiport.
        espdrive_rob_self[0]->_lf_com_width = -2;
        envs[espdrive_main].startup_reactions[startup_reaction_count[espdrive_main]++] = &espdrive_rob_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        espdrive_rob_self[0]->_lf__reaction_0.deadline = NEVER;
        espdrive_rob_self[0]->_lf__reaction_1.deadline = NEVER;
        espdrive_rob_self[0]->_lf__reaction_2.deadline = NEVER;
        espdrive_rob_self[0]->_lf__reaction_3.deadline = NEVER;
        espdrive_rob_self[0]->_lf__reaction_4.deadline = NEVER;
        // Register for transition handling
        envs[espdrive_main].modes->modal_reactor_states[modal_reactor_count[espdrive_main]++] = &((self_base_t*)espdrive_rob_self[0])->_lf__mode_state;
        {
            // ***** Start initializing ESPDrive.rob.motors of class Motors
            espdrive_rob_motors_self[0] = new__motors();
            espdrive_rob_motors_self[0]->base.environment = &envs[espdrive_main];
            bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
            // width of -2 indicates that it is not a multiport.
            espdrive_rob_motors_self[0]->_lf_left_power_width = -2;
            // width of -2 indicates that it is not a multiport.
            espdrive_rob_motors_self[0]->_lf_right_power_width = -2;
            envs[espdrive_main].startup_reactions[startup_reaction_count[espdrive_main]++] = &espdrive_rob_motors_self[0]->_lf__reaction_0;
            SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
            espdrive_rob_motors_self[0]->_lf__reaction_0.deadline = NEVER;
            espdrive_rob_motors_self[0]->_lf__reaction_1.deadline = NEVER;
            espdrive_rob_motors_self[0]->_lf__reaction_2.deadline = NEVER;
            //***** End initializing ESPDrive.rob.motors
        }
        //***** End initializing ESPDrive.rob
    }
    //***** End initializing ESPDrive
    // **** Start deferred initialize for ESPDrive
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of ESPDrive.
        espdrive_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of ESPDrive
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of ESPDrive.
        espdrive_main_self[0]->_lf__reaction_1.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        espdrive_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &espdrive_main_self[0]->base.allocations);
        espdrive_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &espdrive_main_self[0]->base.allocations);
        espdrive_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &espdrive_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                espdrive_main_self[0]->_lf__reaction_1.output_produced[count++] = &espdrive_main_self[0]->_lf_uart.rec.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                espdrive_main_self[0]->_lf__reaction_1.output_produced[count++] = &espdrive_main_self[0]->_lf_d.line0.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of ESPDrive
    
        // **** Start deferred initialize for ESPDrive.uart
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of ESPDrive.uart.
            espdrive_uart_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            espdrive_uart_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &espdrive_uart_self[0]->base.allocations);
            espdrive_uart_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &espdrive_uart_self[0]->base.allocations);
            espdrive_uart_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &espdrive_uart_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    espdrive_uart_self[0]->_lf__reaction_0.output_produced[count++] = &espdrive_uart_self[0]->_lf_mess.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of ESPDrive.uart
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of ESPDrive.uart.
            espdrive_uart_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            espdrive_uart_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &espdrive_uart_self[0]->base.allocations);
            espdrive_uart_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &espdrive_uart_self[0]->base.allocations);
            espdrive_uart_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &espdrive_uart_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    espdrive_uart_self[0]->_lf__reaction_1.output_produced[count++] = &espdrive_uart_self[0]->_lf_mess.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of ESPDrive.uart
        
        }
        // **** End of deferred initialize for ESPDrive.uart
        // **** Start deferred initialize for ESPDrive.d
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of ESPDrive.d.
            espdrive_d_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of ESPDrive.d
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of ESPDrive.d.
            espdrive_d_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of ESPDrive.d
        
        }
        // **** End of deferred initialize for ESPDrive.d
        // **** Start deferred initialize for ESPDrive.rob
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of ESPDrive.rob.
            espdrive_rob_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            espdrive_rob_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &espdrive_rob_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    espdrive_rob_self[0]->_lf__reaction_0.output_produced[count++] = &espdrive_rob_self[0]->_lf_notify.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of ESPDrive.rob
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of ESPDrive.rob.
            espdrive_rob_self[0]->_lf__reaction_1.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            espdrive_rob_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &espdrive_rob_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    espdrive_rob_self[0]->_lf__reaction_1.output_produced[count++] = &espdrive_rob_self[0]->_lf_notify.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    espdrive_rob_self[0]->_lf__reaction_1.output_produced[count++] = &espdrive_rob_self[0]->_lf_motors.left_power.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    espdrive_rob_self[0]->_lf__reaction_1.output_produced[count++] = &espdrive_rob_self[0]->_lf_motors.right_power.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of ESPDrive.rob
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of ESPDrive.rob.
            espdrive_rob_self[0]->_lf__reaction_2.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            espdrive_rob_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &espdrive_rob_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    espdrive_rob_self[0]->_lf__reaction_2.output_produced[count++] = &espdrive_rob_self[0]->_lf_notify.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    espdrive_rob_self[0]->_lf__reaction_2.output_produced[count++] = &espdrive_rob_self[0]->_lf_motors.left_power.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    espdrive_rob_self[0]->_lf__reaction_2.output_produced[count++] = &espdrive_rob_self[0]->_lf_motors.right_power.is_present;
                }
            }
            
            // ** End initialization for reaction 2 of ESPDrive.rob
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of ESPDrive.rob.
            espdrive_rob_self[0]->_lf__reaction_3.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            espdrive_rob_self[0]->_lf__reaction_3.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_3.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_3.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &espdrive_rob_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    espdrive_rob_self[0]->_lf__reaction_3.output_produced[count++] = &espdrive_rob_self[0]->_lf_notify.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    espdrive_rob_self[0]->_lf__reaction_3.output_produced[count++] = &espdrive_rob_self[0]->_lf_motors.left_power.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    espdrive_rob_self[0]->_lf__reaction_3.output_produced[count++] = &espdrive_rob_self[0]->_lf_motors.right_power.is_present;
                }
            }
            
            // ** End initialization for reaction 3 of ESPDrive.rob
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_4 of ESPDrive.rob.
            espdrive_rob_self[0]->_lf__reaction_4.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            espdrive_rob_self[0]->_lf__reaction_4.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_4.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &espdrive_rob_self[0]->base.allocations);
            espdrive_rob_self[0]->_lf__reaction_4.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &espdrive_rob_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    espdrive_rob_self[0]->_lf__reaction_4.output_produced[count++] = &espdrive_rob_self[0]->_lf_notify.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    espdrive_rob_self[0]->_lf__reaction_4.output_produced[count++] = &espdrive_rob_self[0]->_lf_motors.left_power.is_present;
                }
                // Reaction writes to an input of a contained reactor.
                {
                    espdrive_rob_self[0]->_lf__reaction_4.output_produced[count++] = &espdrive_rob_self[0]->_lf_motors.right_power.is_present;
                }
            }
            
            // ** End initialization for reaction 4 of ESPDrive.rob
        
            // **** Start deferred initialize for ESPDrive.rob.motors
            {
            
                // Total number of outputs (single ports and multiport channels)
                // produced by reaction_0 of ESPDrive.rob.motors.
                espdrive_rob_motors_self[0]->_lf__reaction_0.num_outputs = 0;
                {
                    int count = 0; SUPPRESS_UNUSED_WARNING(count);
                }
                
                // ** End initialization for reaction 0 of ESPDrive.rob.motors
                // Total number of outputs (single ports and multiport channels)
                // produced by reaction_1 of ESPDrive.rob.motors.
                espdrive_rob_motors_self[0]->_lf__reaction_1.num_outputs = 0;
                {
                    int count = 0; SUPPRESS_UNUSED_WARNING(count);
                }
                
                // ** End initialization for reaction 1 of ESPDrive.rob.motors
                // Total number of outputs (single ports and multiport channels)
                // produced by reaction_2 of ESPDrive.rob.motors.
                espdrive_rob_motors_self[0]->_lf__reaction_2.num_outputs = 0;
                {
                    int count = 0; SUPPRESS_UNUSED_WARNING(count);
                }
                
                // ** End initialization for reaction 2 of ESPDrive.rob.motors
            
            }
            // **** End of deferred initialize for ESPDrive.rob.motors
        }
        // **** End of deferred initialize for ESPDrive.rob
    }
    // **** End of deferred initialize for ESPDrive
    // **** Start non-nested deferred initialize for ESPDrive
    // Set number of destination reactors for port uart.rec.
    // Iterate over range ESPDrive.uart.rec(0,1)->[ESPDrive.uart.rec(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        espdrive_main_self[src_runtime]->_lf_uart.rec._base.num_destinations = 1;
        espdrive_main_self[src_runtime]->_lf_uart.rec._base.source_reactor = (self_base_t*)espdrive_main_self[src_runtime];
    }
    // Set number of destination reactors for port d.line0.
    // Iterate over range ESPDrive.d.line0(0,1)->[ESPDrive.d.line0(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        espdrive_main_self[src_runtime]->_lf_d.line0._base.num_destinations = 1;
        espdrive_main_self[src_runtime]->_lf_d.line0._base.source_reactor = (self_base_t*)espdrive_main_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ESPDrive.uart.rec(0,1)->[ESPDrive.uart.rec(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of ESPDrive triggers 1 downstream reactions
            // through port ESPDrive.uart.rec.
            espdrive_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of ESPDrive, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.uart.rec
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_main_self[src_runtime]->base.allocations); 
            espdrive_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ESPDrive.d.line0(0,1)->[ESPDrive.d.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of ESPDrive triggers 1 downstream reactions
            // through port ESPDrive.d.line0.
            espdrive_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of ESPDrive, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.d.line0
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_main_self[src_runtime]->base.allocations); 
            espdrive_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ESPDrive.uart.rec(0,1)->[ESPDrive.uart.rec(0,1)] and ESPDrive.uart.rec(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.uart.rec(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.uart.rec's trigger struct.
                espdrive_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_uart_self[dst_runtime]->_lf__rec;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges ESPDrive.d.line0(0,1)->[ESPDrive.d.line0(0,1)] and ESPDrive.d.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.d.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.d.line0's trigger struct.
                espdrive_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_d_self[dst_runtime]->_lf__line0;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for ESPDrive.uart
    
    // For reference counting, set num_destinations for port ESPDrive.uart.mess.
    // Iterate over range ESPDrive.uart.mess(0,1)->[ESPDrive.rob.com(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        espdrive_uart_self[src_runtime]->_lf_mess._base.num_destinations = 1;
        espdrive_uart_self[src_runtime]->_lf_mess._base.source_reactor = (self_base_t*)espdrive_uart_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ESPDrive.uart.mess(0,1)->[ESPDrive.rob.com(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of ESPDrive.uart triggers 1 downstream reactions
            // through port ESPDrive.uart.mess.
            espdrive_uart_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of ESPDrive.uart, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.uart.mess
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_uart_self[src_runtime]->base.allocations); 
            espdrive_uart_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ESPDrive.uart.mess(0,1)->[ESPDrive.rob.com(0,1)] and ESPDrive.rob.com(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.com(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.com's trigger struct.
                espdrive_uart_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_self[dst_runtime]->_lf__com;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ESPDrive.uart.mess(0,1)->[ESPDrive.rob.com(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of ESPDrive.uart triggers 1 downstream reactions
            // through port ESPDrive.uart.mess.
            espdrive_uart_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of ESPDrive.uart, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.uart.mess
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_uart_self[src_runtime]->base.allocations); 
            espdrive_uart_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ESPDrive.uart.mess(0,1)->[ESPDrive.rob.com(0,1)] and ESPDrive.rob.com(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.com(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.com's trigger struct.
                espdrive_uart_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_self[dst_runtime]->_lf__com;
            }
        }
    }
    
    // **** End of non-nested deferred initialize for ESPDrive.uart
    // **** Start non-nested deferred initialize for ESPDrive.d
    
    
    
    
    // **** End of non-nested deferred initialize for ESPDrive.d
    // **** Start non-nested deferred initialize for ESPDrive.rob
    // Set number of destination reactors for port motors.left_power.
    // Iterate over range ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        espdrive_rob_self[src_runtime]->_lf_motors.left_power._base.num_destinations = 1;
        espdrive_rob_self[src_runtime]->_lf_motors.left_power._base.source_reactor = (self_base_t*)espdrive_rob_self[src_runtime];
    }
    // Set number of destination reactors for port motors.right_power.
    // Iterate over range ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        espdrive_rob_self[src_runtime]->_lf_motors.right_power._base.num_destinations = 1;
        espdrive_rob_self[src_runtime]->_lf_motors.right_power._base.source_reactor = (self_base_t*)espdrive_rob_self[src_runtime];
    }
    // For reference counting, set num_destinations for port ESPDrive.rob.notify.
    // Iterate over range ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        espdrive_rob_self[src_runtime]->_lf_notify._base.num_destinations = 1;
        espdrive_rob_self[src_runtime]->_lf_notify._base.source_reactor = (self_base_t*)espdrive_rob_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.notify.
            espdrive_rob_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)] and ESPDrive.d.line2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.d.line2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.d.line2's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_d_self[dst_runtime]->_lf__line2;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.notify.
            espdrive_rob_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.motors.left_power.
            espdrive_rob_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.motors.left_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.motors.right_power.
            espdrive_rob_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.motors.right_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)] and ESPDrive.d.line2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.d.line2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.d.line2's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_d_self[dst_runtime]->_lf__line2;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)] and ESPDrive.rob.motors.left_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.motors.left_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.motors.left_power's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_motors_self[dst_runtime]->_lf__left_power;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)] and ESPDrive.rob.motors.right_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.motors.right_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.motors.right_power's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_motors_self[dst_runtime]->_lf__right_power;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.notify.
            espdrive_rob_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.motors.left_power.
            espdrive_rob_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.motors.left_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.motors.right_power.
            espdrive_rob_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.motors.right_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)] and ESPDrive.d.line2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.d.line2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.d.line2's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_d_self[dst_runtime]->_lf__line2;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)] and ESPDrive.rob.motors.left_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.motors.left_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.motors.left_power's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_motors_self[dst_runtime]->_lf__left_power;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)] and ESPDrive.rob.motors.right_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.motors.right_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.motors.right_power's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_motors_self[dst_runtime]->_lf__right_power;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 3 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.notify.
            espdrive_rob_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 3 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 3 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.motors.left_power.
            espdrive_rob_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 3 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.motors.left_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 3 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.motors.right_power.
            espdrive_rob_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 3 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.motors.right_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)] and ESPDrive.d.line2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.d.line2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.d.line2's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_d_self[dst_runtime]->_lf__line2;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)] and ESPDrive.rob.motors.left_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.motors.left_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.motors.left_power's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_motors_self[dst_runtime]->_lf__left_power;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)] and ESPDrive.rob.motors.right_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.motors.right_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.motors.right_power's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_motors_self[dst_runtime]->_lf__right_power;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 4 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.notify.
            espdrive_rob_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 4 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 4 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.motors.left_power.
            espdrive_rob_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 4 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.motors.left_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 4 of ESPDrive.rob triggers 1 downstream reactions
            // through port ESPDrive.rob.motors.right_power.
            espdrive_rob_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 4 of ESPDrive.rob, allocate an
            // array of trigger pointers for downstream reactions through port ESPDrive.rob.motors.right_power
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &espdrive_rob_self[src_runtime]->base.allocations); 
            espdrive_rob_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)] and ESPDrive.d.line2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.d.line2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.d.line2's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_d_self[dst_runtime]->_lf__line2;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)] and ESPDrive.rob.motors.left_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.motors.left_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.motors.left_power's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_motors_self[dst_runtime]->_lf__left_power;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)] and ESPDrive.rob.motors.right_power(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ESPDrive.rob.motors.right_power(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ESPDrive.rob.motors.right_power's trigger struct.
                espdrive_rob_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &espdrive_rob_motors_self[dst_runtime]->_lf__right_power;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for ESPDrive.rob.motors
    
    
    
    
    // **** End of non-nested deferred initialize for ESPDrive.rob.motors
    // **** End of non-nested deferred initialize for ESPDrive.rob
    // **** End of non-nested deferred initialize for ESPDrive
    // Connect inputs and outputs for reactor ESPDrive.
    // Connect inputs and outputs for reactor ESPDrive.uart.
    // Connect ESPDrive.uart.rec(0,1)->[ESPDrive.uart.rec(0,1)] to port ESPDrive.uart.rec(0,1)
    // Iterate over ranges ESPDrive.uart.rec(0,1)->[ESPDrive.uart.rec(0,1)] and ESPDrive.uart.rec(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ESPDrive.uart.rec(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            espdrive_uart_self[dst_runtime]->_lf_rec = (_uartrec_rec_t*)&espdrive_main_self[src_runtime]->_lf_uart.rec;
        }
    }
    // Connect ESPDrive.uart.mess(0,1)->[ESPDrive.rob.com(0,1)] to port ESPDrive.rob.com(0,1)
    // Iterate over ranges ESPDrive.uart.mess(0,1)->[ESPDrive.rob.com(0,1)] and ESPDrive.rob.com(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ESPDrive.rob.com(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            espdrive_rob_self[dst_runtime]->_lf_com = (_robot_com_t*)&espdrive_uart_self[src_runtime]->_lf_mess;
        }
    }
    // Connect inputs and outputs for reactor ESPDrive.d.
    // Connect ESPDrive.d.line0(0,1)->[ESPDrive.d.line0(0,1)] to port ESPDrive.d.line0(0,1)
    // Iterate over ranges ESPDrive.d.line0(0,1)->[ESPDrive.d.line0(0,1)] and ESPDrive.d.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ESPDrive.d.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            espdrive_d_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&espdrive_main_self[src_runtime]->_lf_d.line0;
        }
    }
    // Connect inputs and outputs for reactor ESPDrive.rob.
    // Connect ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)] to port ESPDrive.d.line2(0,1)
    // Iterate over ranges ESPDrive.rob.notify(0,1)->[ESPDrive.d.line2(0,1)] and ESPDrive.d.line2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ESPDrive.d.line2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            espdrive_d_self[dst_runtime]->_lf_line2 = (_display_line2_t*)&espdrive_rob_self[src_runtime]->_lf_notify;
        }
    }
    // Connect inputs and outputs for reactor ESPDrive.rob.motors.
    // Connect ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)] to port ESPDrive.rob.motors.left_power(0,1)
    // Iterate over ranges ESPDrive.rob.motors.left_power(0,1)->[ESPDrive.rob.motors.left_power(0,1)] and ESPDrive.rob.motors.left_power(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ESPDrive.rob.motors.left_power(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            espdrive_rob_motors_self[dst_runtime]->_lf_left_power = (_motors_left_power_t*)&espdrive_rob_self[src_runtime]->_lf_motors.left_power;
        }
    }
    // Connect ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)] to port ESPDrive.rob.motors.right_power(0,1)
    // Iterate over ranges ESPDrive.rob.motors.right_power(0,1)->[ESPDrive.rob.motors.right_power(0,1)] and ESPDrive.rob.motors.right_power(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ESPDrive.rob.motors.right_power(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            espdrive_rob_motors_self[dst_runtime]->_lf_right_power = (_motors_right_power_t*)&espdrive_rob_self[src_runtime]->_lf_motors.right_power;
        }
    }
    {
    }
    {
    }
    {
        {
        }
        // Add port ESPDrive.rob.motors.left_power to array of is_present fields.
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            {
                {
                    envs[espdrive_main].is_present_fields[0 + count] = &espdrive_rob_self[0]->_lf_motors.left_power.is_present;
                    #ifdef FEDERATED_DECENTRALIZED
                    envs[espdrive_main]._lf_intended_tag_fields[0 + count] = &espdrive_rob_self[0]->_lf_motors.left_power.intended_tag;
                    #endif // FEDERATED_DECENTRALIZED
                    count++;
                }
            }
        }
        // Add port ESPDrive.rob.motors.right_power to array of is_present fields.
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            {
                {
                    envs[espdrive_main].is_present_fields[1 + count] = &espdrive_rob_self[0]->_lf_motors.right_power.is_present;
                    #ifdef FEDERATED_DECENTRALIZED
                    envs[espdrive_main]._lf_intended_tag_fields[1 + count] = &espdrive_rob_self[0]->_lf_motors.right_power.intended_tag;
                    #endif // FEDERATED_DECENTRALIZED
                    count++;
                }
            }
        }
    }
    // Add port ESPDrive.uart.rec to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[espdrive_main].is_present_fields[2 + count] = &espdrive_main_self[0]->_lf_uart.rec.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[espdrive_main]._lf_intended_tag_fields[2 + count] = &espdrive_main_self[0]->_lf_uart.rec.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port ESPDrive.d.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[espdrive_main].is_present_fields[3 + count] = &espdrive_main_self[0]->_lf_d.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[espdrive_main]._lf_intended_tag_fields[3 + count] = &espdrive_main_self[0]->_lf_d.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port ESPDrive.uart.mess to array of is_present fields.
            envs[espdrive_main].is_present_fields[4 + count] = &espdrive_uart_self[0]->_lf_mess.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port ESPDrive.uart.mess to array of intended_tag fields.
            envs[espdrive_main]._lf_intended_tag_fields[4 + count] = &espdrive_uart_self[0]->_lf_mess.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port ESPDrive.rob.notify to array of is_present fields.
            envs[espdrive_main].is_present_fields[5 + count] = &espdrive_rob_self[0]->_lf_notify.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port ESPDrive.rob.notify to array of intended_tag fields.
            envs[espdrive_main]._lf_intended_tag_fields[5 + count] = &espdrive_rob_self[0]->_lf_notify.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance ESPDrive
    {
        espdrive_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        espdrive_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        espdrive_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        espdrive_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
    
        // Set reaction priorities for ReactorInstance ESPDrive.uart
        {
            espdrive_uart_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            espdrive_uart_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            espdrive_uart_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            espdrive_uart_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
        }
    
    
        // Set reaction priorities for ReactorInstance ESPDrive.d
        {
            espdrive_d_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            espdrive_d_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            espdrive_d_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 7 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            espdrive_d_self[0]->_lf__reaction_1.index = 0xffffffffffff0007LL;
        }
    
    
        // Set reaction priorities for ReactorInstance ESPDrive.rob
        {
            espdrive_rob_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            espdrive_rob_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            espdrive_rob_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            espdrive_rob_self[0]->_lf__reaction_1.index = 0xffffffffffff0003LL;
            espdrive_rob_self[0]->_lf__reaction_2.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            espdrive_rob_self[0]->_lf__reaction_2.index = 0xffffffffffff0004LL;
            espdrive_rob_self[0]->_lf__reaction_3.chain_id = 1;
            // index is the OR of level 5 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            espdrive_rob_self[0]->_lf__reaction_3.index = 0xffffffffffff0005LL;
            espdrive_rob_self[0]->_lf__reaction_4.chain_id = 1;
            // index is the OR of level 6 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            espdrive_rob_self[0]->_lf__reaction_4.index = 0xffffffffffff0006LL;
        
            // Set reaction priorities for ReactorInstance ESPDrive.rob.motors
            {
                espdrive_rob_motors_self[0]->_lf__reaction_0.chain_id = 1;
                // index is the OR of level 0 and 
                // deadline 9223372036854775807 shifted left 16 bits.
                espdrive_rob_motors_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
                espdrive_rob_motors_self[0]->_lf__reaction_1.chain_id = 1;
                // index is the OR of level 7 and 
                // deadline 9223372036854775807 shifted left 16 bits.
                espdrive_rob_motors_self[0]->_lf__reaction_1.index = 0xffffffffffff0007LL;
                espdrive_rob_motors_self[0]->_lf__reaction_2.chain_id = 1;
                // index is the OR of level 8 and 
                // deadline 9223372036854775807 shifted left 16 bits.
                espdrive_rob_motors_self[0]->_lf__reaction_2.index = 0xffffffffffff0008LL;
            }
        
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
